import 'dart:ui';

import 'package:flutter/foundation.dart';

class AppSettingsProvider extends ChangeNotifier {
  AppSettingsProvider() {
    configureForLocale(PlatformDispatcher.instance.locale);
  }

  String _languageCode = 'en';
  List<String> _availableLanguageCodes = <String>['en', 'hi', 'ta'];
  double _textScaleFactor = 1.0;
  bool _hapticsEnabled = true;
  bool _sosFlashEnabled = false;
  bool _highContrastEnabled = false;
  bool _notificationsEnabled = true;

  static const Map<String, List<String>> _regionLanguagePresets = <String, List<String>>{
    'IN:en': <String>['en', 'hi', 'ta', 'ml', 'mr', 'te', 'kn', 'bn', 'gu', 'pa', 'or'],
    'IN:hi': <String>['hi', 'en', 'ta', 'te', 'kn'],
    'IN:ta': <String>['ta', 'en', 'hi', 'ml', 'te'],
    'IN:te': <String>['te', 'en', 'hi', 'ta', 'kn'],
    'IN:kn': <String>['kn', 'en', 'hi', 'ta', 'ml'],
    'IN:ml': <String>['ml', 'en', 'hi', 'kn'],
    'IN:mr': <String>['mr', 'en', 'hi', 'gu'],
    'IN:bn': <String>['bn', 'en', 'hi', 'or'],
    'IN:gu': <String>['gu', 'en', 'hi', 'mr'],
    'IN:pa': <String>['pa', 'en', 'hi', 'or'],
    'IN:or': <String>['or', 'en', 'hi', 'bn'],
    'CN:zh': <String>['zh', 'en'],
    'JP:ja': <String>['ja', 'en'],
    'KR:ko': <String>['ko', 'en'],
  };

  static const Map<String, String> _languageLabels = {
    'en': 'English',
    'hi': 'Hindi',
    'bn': 'Bengali',
    'gu': 'Gujarati',
    'kn': 'Kannada',
    'mr': 'Marathi',
    'or': 'Odia',
    'pa': 'Punjabi',
    'ta': 'Tamil',
    'te': 'Telugu',
    'ml': 'Malayalam',
    'zh': 'Chinese',
    'ja': 'Japanese',
    'ko': 'Korean',
  };

  static const Map<String, String> _nativeLanguageLabels = {
    'en': 'English',
    'hi': 'हिंदी',
    'bn': 'বাংলা',
    'gu': 'ગુજરાતી',
    'kn': 'ಕನ್ನಡ',
    'mr': 'मराठी',
    'or': 'ଓଡ଼ିଆ',
    'pa': 'ਪੰਜਾਬੀ',
    'ta': 'தமிழ்',
    'te': 'తెలుగు',
    'ml': 'മലയാളം',
    'zh': '中文',
    'ja': '日本語',
    'ko': '한국어',
  };

  String get languageCode => _languageCode;
  List<String> get availableLanguageCodes =>
      List<String>.unmodifiable(_availableLanguageCodes);
  String get selectedLanguageLabel =>
      _languageLabels[_languageCode] ?? _languageCode;
  double get textScaleFactor => _textScaleFactor;
  bool get hapticsEnabled => _hapticsEnabled;
  bool get sosFlashEnabled => _sosFlashEnabled;
  bool get highContrastEnabled => _highContrastEnabled;
  bool get notificationsEnabled => _notificationsEnabled;

  String languageLabel(String code) {
    final native = _nativeLanguageLabels[code] ?? code;
    final english = _languageLabels[code];
    if (english == null || english == native) {
      return native;
    }
    return '$native ($english)';
  }

  static final Map<String, Map<String, String>> _strings = {
    'en': {
      'app_title': 'RescueLink',
      'emergency_prompt': 'In an Emergency?',
      'emergency_subtitle': 'Press the SOS button below to alert nearby responders',
      'become_responder': 'Become A Responder',
      'location_ready': 'Location: Ready',
      'location_not_ready': 'Location: Not Ready',
      'user_info': 'User Info',
      'total_responders': 'Total Responders',
      'nearby_5km': 'Nearby (5km)',
      'sign_in_title': 'RescueLink Sign In',
      'sign_in': 'Sign In',
      'create_account': 'Create Account',
      'continue_guest': 'Continue as Guest (Anonymous)',
      'language': 'Language',
      // Button labels
      'button_cancel_sos': 'Cancel SOS',
      'button_view_map': 'View Map',
      'button_open_chat': 'Open Chat',
      'button_call_emergency': 'Call 112',
      'button_sign_out': 'Sign Out',
      'button_people_needing_help': 'People Needing Help',
      'button_voice_test': 'Voice Test',
      'button_flash_test': 'Flash Test',
      'button_responder_register': 'Register as Responder',
      'button_force_critical': 'Force Critical',
      'button_powered_by_gemini': 'Powered by Gemini',
      'button_select_document': 'Select Document',
      'button_upload': 'Upload',
      'button_accept': 'Accept',
      'button_reject': 'Reject',
      'auth_sign_in_title': 'Sign in to RescueLink',
      'auth_create_account_prompt': 'Create account',
      'auth_already_have_account': 'Already have an account? Sign in',
      'auth_need_account': 'Need an account? Create one',
      'auth_display_name': 'Display Name',
      'auth_phone_number': 'Phone Number (optional, used for responder auto-fill)',
      'auth_email': 'Email',
      'auth_password': 'Password',
      'title_responder_registration': 'Responder Registration',
      'responder_registration_headline': 'Join local emergency response',
      'responder_registration_description': 'Your profile helps RescueLink find and match you during SOS events.',
      'responder_registration_profile_help': 'Name and phone are prefilled from your login profile. Add your responder profile so AI can route requests better during crisis and daily care.',
      'responder_registration_verification_note': 'Verification is self-declared for now. Admin review can be added later without slowing down registration.',
      'label_full_name': 'Full Name',
      'label_phone_number': 'Phone Number',
      'label_primary_skill': 'Primary Skill',
      'label_responder_type': 'Responder Type',
      'label_id_upload': 'ID Document Upload (Optional)',
      'responder_registration_id_description': 'Upload your official ID (Passport, Driver License, or National ID) for verification. Accepted formats: PDF, JPG, PNG',
      'document_uploaded_successfully': 'Document uploaded successfully',
      'label_document_name': 'ID Document',
      'status_uploading': 'Uploading...',
      'prompt_select_document_first': 'Please select a document first',
      'prompt_sign_in_first': 'Please sign in first',
      'error_document_upload_failed': 'Failed to upload document: {error}',
      'prompt_getting_location': 'Getting your location...',
      'prompt_location_required': 'Location is required to register as responder.',
      'snackbar_responder_registered': 'You are now registered as a responder.',
      'error_registration': 'Registration error: {error}',
      'error_please_enter_name': 'Please enter your name',
      'error_please_enter_phone': 'Please enter your phone number',
      'error_valid_phone_number': 'Please enter a valid phone number',
      'auth_enter_display_name': 'Enter your display name',
      'auth_enter_email': 'Enter your email',
      'auth_enter_valid_email': 'Enter a valid email',
      'auth_password_min_length': 'Password must be at least 6 characters',
      'auth_phone_otp_disabled': 'Phone OTP login is currently disabled in this build to avoid billing dependency. Register with email and optional phone number.',
      'auth_no_email': 'No email',
      'auth_app_user': 'RescueLink User',
      // Screen titles
      'title_my_sos_chats': 'My SOS Chats',
      'title_responder_alerts': 'Responder Alerts',
      'title_map': 'Emergency Map',
      'title_profile': 'Profile',
      'title_settings': 'Settings',
      'title_accessibility': 'Accessibility Settings',
      'profile_my_responder_profile': 'My Responder Profile',
      'profile_ai_assistant': 'AI Assistant Profile',
      'profile_responder_profile': 'Responder Profile',
      'profile_verified_responder': 'Verified responder',
      'profile_not_verified_yet': 'Not verified yet',
      'profile_available_now': 'Available now',
      'profile_currently_offline': 'Currently offline',
      'profile_rescues': 'Rescues',
      'profile_rating': 'Rating',
      'profile_reviews': 'Reviews',
      'profile_identity': 'Identity',
      'profile_ai_core': 'AI Core',
      'profile_verified': 'Verified',
      'profile_unverified': 'Unverified',
      'profile_contact': 'Contact',
      'profile_call': 'Call',
      'profile_message': 'Message',
      'profile_community_reviews': 'Community Reviews',
      'profile_rate_review': 'Rate & Review',
      'profile_no_reviews_yet': 'No reviews yet. Be the first to share your experience!',
      'profile_edit_delete': 'Edit/Delete',
      'profile_no_phone_number': 'No phone number available for this responder.',
      'profile_could_not_open_dialer': 'Could not open the dialer on this device.',
      'profile_no_messaging_number': 'No messaging number available for this responder.',
      'profile_messaging_not_supported': 'Messaging is not supported on this device yet.',
      'profile_review_title': 'Review {name}',
      'profile_give_rating_review': 'Give both a rating and a review.',
      'profile_share_experience': 'Share your experience with this responder...',
      'profile_unable_delete_review': 'Unable to delete review: ',
      'profile_review_deleted': 'Review deleted.',
      'profile_cancel': 'Cancel',
      'profile_unable_save_review': 'Unable to save review: ',
      'profile_review_saved': 'Review saved.',
      'profile_save_review': 'Save Review',
      'profile_this_is_your_view': 'This is your responder profile view.',
      'responder_skill_medical_emergency': 'Medical Emergency',
      'responder_skill_fire_and_rescue': 'Fire & Rescue',
      'responder_skill_search_and_rescue': 'Search & Rescue',
      'responder_skill_shelter_and_evacuation': 'Shelter & Evacuation',
      'responder_skill_food_and_water_supply': 'Food & Water Supply',
      'responder_skill_elderly_assist': 'Elderly Assist',
      'responder_skill_women_safety': 'Women Safety',
      'responder_skill_child_safety': 'Child Safety',
      'responder_skill_essential_medicines': 'Essential Medicines',
      'responder_skill_mobility_support': 'Mobility Support',
      'responder_skill_communication_relay': 'Communication Relay',
      'responder_skill_logistics_and_transport': 'Logistics & Transport',
      'responder_skill_general_support': 'General Support',
      'responder_type_community_volunteer': 'Community Volunteer',
      'responder_type_medical_professional': 'Medical Professional',
      'responder_type_firefighter': 'Firefighter',
      'responder_type_police': 'Police',
      'responder_type_off_duty_authority': 'Off-duty Authority',
      'responder_type_civil_defense': 'Civil Defense',
      'responder_type_ngo_worker': 'NGO Worker',
      'responder_type_logistics_provider': 'Logistics Provider',
      'responder_type_shelter_host': 'Shelter Host',
      'sos_button_label': 'SOS',
      'sos_button_tap': 'TAP',
      'sos_button_accessibility_label': 'Emergency SOS button',
      'sos_button_accessibility_hint': 'Tap to alert nearby responders. Long press to cancel.',
      // Filter chips
      'filter_active': 'Active',
      'filter_cancelled': 'Cancelled',
      'filter_all': 'All',
      // Search & input hints
      'hint_search_case': 'Search by case ID or message',
      'hint_emergency_context': 'Describe emergency situation',
      'chat_type_message': 'Type a message',
      'chat_stop_dictation': 'Stop dictation',
      'chat_start_dictation': 'Start dictation',
      'chat_microphone_required': 'Microphone permission is required for audio attach.',
      'chat_fetching_profile': 'Fetching responder profile...',
      'chat_profile_not_found': 'Responder profile not found.',
      'chat_failed_load_profile': 'Failed to load profile: ',
      'chat_tap_avatar_profile': 'Tap avatar for profile',
      'chat_ai_cannot_review': 'AI Assistant cannot be reviewed.',
      'chat_request_status': 'Request {status} for {name}',
      'chat_view_profile': 'View Profile',
      'chat_review_name': 'Review {name}',
      'chat_describe_experience': 'Describe your experience...',
      'chat_review_saved_for': 'Review saved for {name}',
      'chat_remove_responder_confirm': 'Are you sure you want to remove {name} from this conversation? They will not be able to rejoin without your approval.',
      'chat_responder_removed': '{name} has been removed.',
      'chat_reply_to_name': 'Reply to {name}',
      'chat_request_status_snackbar': 'Request {status} for {name}',
      'chat_ai_assistant_label': 'AI assistant',
      'chat_rescue_link_ai': 'RescueLink AI',
      // Labels
      'label_text_size': 'Text Size',
      'label_haptics': 'Haptics',
      'label_high_contrast': 'High Contrast Mode',
      'label_flashlight': 'Flashlight',
      'label_flashlight_hint': 'Use the device flash to signal for help or light your path.',
      'label_notifications_hint': 'Receive alerts for nearby responders and case updates.',
      'button_reset': 'Reset',
      'label_notifications': 'Notifications',
      'label_nearby_responders': 'Nearby Responders',
      'label_responder_online': 'Responder Online',
      // Status & Messages
      'status_sos_received': '✓ SOS Received',
      'status_requesting_location': 'Requesting your location...',
      'status_no_location': 'Unable to determine location. Please try again.',
      'status_please_sign_in': 'Please sign in to view chats.',
      'status_chat_not_ready': 'Chat is not ready yet.',
      'status_not_signed_in': 'Not signed in',
      'status_no_sos_chats_found': 'No SOS chats found yet.',
      'status_location_ready': 'Location Ready',
      'status_location_not_ready': 'Location Not Ready',
      'status_sos_activated': 'SOS activated. Nearby responders have been notified.',
      'status_sos_photo_upload_failed': 'Photo upload failed: ',
      'status_sos_audio_failed': 'Audio attach failed: ',
      'status_sos_setup_refreshed': 'Chat setup refreshed. You can try sending now.',
      // Error messages
      'error_chat_setup_failed': 'Chat setup failed. Please try again.',
      'error_sos_incomplete': 'SOS could not complete. Please try again.',
      'error_failed_load_chats': 'Failed to load chats',
      // Dialog & confirmation
      'dialog_sos_confirmation': 'SOS Triggered',
      'dialog_attachment_photo': 'Photo attached',
      'dialog_attachment_voice': 'Voice clip attached',
      'dialog_sent_attachment': 'Sent an attachment',
      'map_navigation_map': 'Navigation Map',
      'map_responders_map': 'Responders Map',
      'map_center_location': 'Center on my location',
      'map_location_not_available': 'Location not available',
      'map_turn_on_location': 'Turn On Location',
      'map_grant_permission': 'Grant Permission',
      'map_retry': 'Retry',
      'map_destination': 'Destination: {title}',
      'map_help_request': 'Help Request',
      'map_nearby_responders': 'Nearby Responders (5km radius)',
      'map_open_navigation': 'Open Turn-by-Turn Navigation',
      'map_no_responders_nearby': 'No responders nearby',
      'map_away_km': '{distance} km away',
      'map_view_profile': 'View profile',
      // Menu items
      'menu_disable_notifications': 'Disable notifications for this chat',
      'menu_enable_notifications': 'Enable notifications for this chat',
      'menu_delete_chat': 'Delete chat',
      'menu_mute': 'Mute',
      'menu_unmute': 'Unmute',
      'status_no_open_requests': 'No open requests right now.',
      'status_no_matching_requests': 'No matching requests near you right now.',
      'filter_all_active': 'All Active',
      'filter_joined_by_me': 'Joined By Me',
      'view_details_and_media': 'View details & media',
      'reporter_message': 'Reporter message:',
      'voice_transcript': 'Voice transcript:',
      'open_image': 'Open image',
      'open_external': 'Open external',
      'play_audio': 'Play audio',
      'stop_audio': 'Stop audio',
      'navigate': 'Navigate',
      'image_unavailable_preview': 'Image unavailable in preview. Use Open image.',
      'no_nearby_responders_hint': 'No nearby responders yet. Use emergency call/SMS as secondary backup.',
      'analysis_results': 'Analysis Results',
      'category_label': 'Category',
      'severity_label': 'Severity',
      'skill_match': 'Skill Match',
      'manual_override_critical': 'Manual override: CRITICAL',
      'human_review_recommended': 'Human review recommended',
      'recommended_actions': 'Recommended Actions',
      'offline_mode_active': 'Offline Mode (AI Fallback Active)',
      'category_fire_emergency': 'Fire Emergency',
      'category_medical_emergency': 'Medical Emergency',
      'category_disaster_evacuation': 'Disaster Evacuation',
      'category_essential_supply_need': 'Essential Supply Need',
      'category_elderly_assistance': 'Elderly Assistance',
      'category_women_safety': 'Women Safety',
      'category_child_safety': 'Child Safety',
      'category_search_and_rescue': 'Search & Rescue',
      'category_water_rescue_emergency': 'Water Rescue Emergency',
      'category_railway_hazard_emergency': 'Railway Hazard Emergency',
      'category_entrapment_rescue': 'Entrapment Rescue',
      'category_animal_insect_attack': 'Animal/Insect Attack',
      'category_general_emergency': 'General Emergency',
      'category_medical_safety_emergency': 'Medical Safety Emergency',
      'category_rescue_emergency': 'Rescue Emergency',
      'skill_fire_rescue': 'Fire & Rescue',
      'skill_medical_emergency': 'Medical Emergency',
      'skill_search_rescue': 'Search & Rescue',
      'skill_shelter_evacuation': 'Shelter & Evacuation',
      'skill_food_water_supply': 'Food & Water Supply',
      'skill_elderly_assist': 'Elderly Assist',
      'skill_women_safety': 'Women Safety',
      'skill_child_safety': 'Child Safety',
      'skill_general_support': 'General Support',
      'sos_default_message': 'Potential emergency needs urgent support.',
      'chat_group_title': 'RescueLink Group Chat',
      'chat_online_count': '{count} Online',
      'chat_sos_cancelled': 'This SOS has been cancelled.',
      'chat_failed_load_messages': 'Failed to load messages',
      'chat_no_messages_yet': 'No messages yet. Start the conversation.',
      'chat_ask_ai_assistant': 'Ask AI Assistant',
      'chat_actions_tooltip': 'Chat actions',
      'chat_view_responders': 'View Responders',
      'chat_delete_chat_victim': 'Delete Chat (Victim)',
      'chat_leave_chat_responder': 'Leave Chat (Responder)',
      'chat_active_responders': 'Active Responders ({count})',
      'button_responder_dashboard': 'Responder Dashboard',
      'label_emergency_details_optional': 'Emergency details (optional)',
      'hint_emergency_details_example': 'Example: elderly person fell, flood nearby, child missing, no transport',
      'tooltip_voice_to_text': 'Voice to text',
      'tooltip_stop_voice_to_text': 'Stop voice-to-text',
      'tooltip_record_voice_clip': 'Record voice clip',
      'tooltip_stop_voice_clip': 'Stop voice clip',
      'tooltip_play_preview': 'Play preview',
      'tooltip_stop_preview': 'Stop preview',
      'tooltip_capture_photo': 'Capture photo',
      'attachment_photo': 'Photo attachment',
      'semantics_view_attached_photo': 'View attached photo',
      'attachment_voice': 'Voice attachment',
      'semantics_play_attached_voice_clip': 'Play attached voice clip',
      'status_visual_ai_disabled': 'Visual AI disabled (Local fallback)',
      'status_visual_ai_enabled': 'Visual AI enabled (Gemini multimodal)',
      'status_transcription_cloud_enabled': 'Transcription: Cloud assist enabled',
      'status_transcription_ondevice_free': 'Transcription: On-device only (free mode)',
      'status_transcript_ready': 'Transcript ready',
      'status_transcript_percent': 'Transcript {pct}%',
      'status_local_fallback': 'Local Fallback',
      'chat_emergency_overview': 'Emergency Overview',
      'home_select_language': 'Select Language',
      'home_choose_preferred_language': 'Choose your preferred language',
      'account_anonymous_session': 'Anonymous Session',
      'account_registered_account': 'Registered Account',
      'account_signin_create': 'Sign In / Create Account',
      'responder_deregister': 'De-register as responder',
      'accessibility_announcement_text': 'Accessibility test announcement. SOS button is centered below information cards.',
      'accessibility_announcement_sent': 'Screen reader announcement sent.',
      'flash_test_completed': 'Flash pulse test completed.',
      'notification_permission_not_granted': 'Notification permission not granted.',
      'comms_simulation_title': 'Comms Simulation',
      'comms_simulate_tower_failure': 'Simulate tower failure',
      'comms_device_supports_satellite': 'Device supports satellite',
      'comms_simulated_capability': 'Simulated capability',
      'comms_simulation_info': 'This simulation allows testing disaster or lockdown connectivity fallback without real mesh or satellite hardware.',
      'label_route': 'Route',
      'comms_mode_auto': 'Auto',
      'comms_mode_internet': 'Internet',
      'comms_mode_mesh_simulated': 'Mesh (Simulated)',
      'comms_mode_satellite_simulated': 'Satellite (Simulated)',
      'comms_route_internet': 'Internet route',
      'comms_route_mesh_simulated': 'Mesh relay (simulated)',
      'comms_route_satellite_simulated': 'Satellite uplink (simulated)',
      'label_case_id': 'Case ID',
      'status_cancelled': 'CANCELLED',
      'dialog_delete_cancelled_chat_title': 'Delete cancelled chat?',
      'dialog_delete_cancelled_chat_body': 'This permanently deletes this cancelled SOS chat and all messages from the database.',
      'button_keep': 'Keep',
      'button_delete': 'Delete',
      'tooltip_delete_cancelled_chat': 'Delete cancelled chat',
      'snackbar_cancelled_chat_deleted': 'Cancelled chat deleted.',
      'snackbar_failed_delete_chat': 'Failed to delete chat. Please retry.',
      'dialog_leave_conversation_title': 'Leave this conversation?',
      'dialog_leave_conversation_body': 'If you leave, you will need approval to rejoin this chat later.',
      'button_leave': 'Leave',
      'snackbar_conversation_removed': 'Conversation removed from your list.',
      'button_cancel': 'Cancel',
      'status_no_active_chats': 'No active chats right now.',
      'status_no_joined_chats': 'You have not joined any chats yet.',
      'status_no_matching_chats': 'No chats match your search.',
      'responder_chat_showing_joined': 'Showing {total} chats • Joined {joined}',
      'responder_chat_tap_hint': 'Tap a chat to open conversation. Join happens inside chat if needed.',
      'status_no_sos_message_available': 'No SOS message available',
    },
    'hi': {
      'app_title': 'रेस्क्यूलिंक',
      'emergency_prompt': 'क्या आप आपात स्थिति में हैं?',
      'emergency_subtitle': 'नीचे SOS बटन दबाकर नज़दीकी रिस्पॉन्डर्स को अलर्ट करें',
      'become_responder': 'रिस्पॉन्डर बनें',
      'location_ready': 'लोकेशन: तैयार',
      'location_not_ready': 'लोकेशन: तैयार नहीं',
      'user_info': 'उपयोगकर्ता जानकारी',
      'total_responders': 'कुल रिस्पॉन्डर्स',
      'nearby_5km': 'नज़दीक (5 किमी)',
      'sign_in_title': 'रेस्क्यूलिंक साइन इन',
      'sign_in': 'साइन इन',
      'create_account': 'खाता बनाएं',
      'continue_guest': 'गेस्ट के रूप में जारी रखें',
      'language': 'भाषा',
      // Button labels
      'button_cancel_sos': 'SOS रद्द करें',
      'button_view_map': 'मानचित्र देखें',
      'button_open_chat': 'चैट खोलें',
      'button_call_emergency': '112 को कॉल करें',
      'button_sign_out': 'साइन आउट',
      'button_people_needing_help': 'मदद की जरूरत वाले लोग',
      'button_voice_test': 'आवाज़ परीक्षण',
      'button_flash_test': 'फ्लैश परीक्षण',
      'button_responder_register': 'प्रतिक्रिया कर्ता के रूप में पंजीकृत करें',
      'button_accept': 'स्वीकार करें',
      'button_reject': 'अस्वीकार करें',
      // Screen titles
      'title_my_sos_chats': 'मेरे SOS चैट',
      'title_responder_alerts': 'प्रतिक्रिया कर्ता सतर्कताएं',
      'title_map': 'आपातकालीन मानचित्र',
      'title_profile': 'प्रोफाइल',
      'title_settings': 'सेटिंग्स',
      'title_accessibility': 'पहुंच सेटिंग्स',
      // Filter chips
      'filter_active': 'सक्रिय',
      'filter_cancelled': 'रद्द किया गया',
      'filter_all': 'सभी',
      // Search & input hints
      'hint_search_case': 'केस आईडी या संदेश द्वारा खोजें',
      'hint_emergency_context': 'आपातकालीन स्थिति का वर्णन करें',
      'chat_type_message': 'एक संदेश टाइप करें',
      // Labels
      'label_text_size': 'पाठ आकार',
      'label_haptics': 'कंपन',
      'label_high_contrast': 'उच्च विपरीतता मोड',
      'label_flashlight': 'फ़्लैशलाइट',
      'label_flashlight_hint': 'मदद के लिए संकेत भेजने या अपना मार्ग रोशन करने के लिए डिवाइस फ्लैश का उपयोग करें।',
      'label_notifications_hint': 'नज़दीकी प्रतिक्रिया कर्ताओं और केस अपडेट के लिए अलर्ट प्राप्त करें।',
      'button_reset': 'रीसेट',
      'label_notifications': 'सूचनाएं',
      'label_nearby_responders': 'नज़दीकी प्रतिक्रिया कर्ता',
      'label_responder_online': 'प्रतिक्रिया कर्ता ऑनलाइन',
      // Status & Messages
      'status_sos_received': '✓ SOS प्राप्त',
      'status_requesting_location': 'आपकी लोकेशन मांग रहे हैं...',
      'status_no_location': 'लोकेशन निर्धारित नहीं की जा सकी। कृपया पुनः प्रयास करें।',
      'status_please_sign_in': 'चैट देखने के लिए कृपया साइन इन करें।',
      'status_chat_not_ready': 'चैट अभी तैयार नहीं है।',
      'status_not_signed_in': 'साइन इन नहीं किया गया',
      'status_location_ready': 'लोकेशन तैयार',
      'status_location_not_ready': 'लोकेशन तैयार नहीं',
      'status_sos_activated': 'SOS सक्रिय किया गया। नज़दीकी प्रतिक्रिया कर्ताओं को सूचित किया गया।',
      'status_sos_photo_upload_failed': 'फ़ोटो अपलोड विफल: ',
      'status_sos_audio_failed': 'ऑडियो संलग्न विफल: ',
      'status_sos_setup_refreshed': 'चैट सेटअप रीफ्रेश किया गया। आप अब भेजने का प्रयास कर सकते हैं।',
      // Error messages
      'error_chat_setup_failed': 'चैट सेटअप विफल। कृपया पुनः प्रयास करें।',
      'error_sos_incomplete': 'SOS पूरा नहीं हो सका। कृपया पुनः प्रयास करें।',
      'error_failed_load_chats': 'चैट लोड करने में विफल',
      // Dialog & confirmation
      'dialog_sos_confirmation': 'SOS ट्रिगर किया गया',
      'dialog_attachment_photo': 'फ़ोटो संलग्न',
      'dialog_attachment_voice': 'वॉयस क्लिप संलग्न',
      'dialog_sent_attachment': 'संलग्नक भेजा गया',
      // Menu items
      'menu_disable_notifications': 'इस चैट के लिए सूचनाएं अक्षम करें',
      'menu_enable_notifications': 'इस चैट के लिए सूचनाएं सक्षम करें',
      'menu_delete_chat': 'चैट हटाएं',
      'menu_mute': 'म्यूट करें',
      'menu_unmute': 'म्यूट हटाएं',
      'button_force_critical': 'त्वरित कार्रवाई करें',
      'button_powered_by_gemini': 'Gemini द्वारा संचालित',
      'button_select_document': 'दस्तावेज़ चुनें',
      'button_upload': 'अपलोड करें',
      'label_id_upload': 'आईडी दस्तावेज़ अपलोड (वैकल्पिक)',
      'responder_registration_id_description': 'पुष्टिकरण के लिए अपना आधिकारिक आईडी (पासपोर्ट, ड्राइवर लाइसेंस, या राष्ट्रीय आईडी) अपलोड करें। स्वीकृत फ़ॉर्मेट: PDF, JPG, PNG',
      'document_uploaded_successfully': 'दस्तावेज़ सफलतापूर्वक अपलोड किया गया',
      'label_document_name': 'आईडी दस्तावेज़',
      'status_uploading': 'अपलोड हो रहा है...',
      'prompt_select_document_first': 'कृपया पहले एक दस्तावेज़ चुनें',
      'prompt_sign_in_first': 'कृपया पहले साइन इन करें',
      'error_document_upload_failed': 'दस्तावेज़ अपलोड विफल: {error}',
      'sos_button_label': 'SOS',
      'sos_button_tap': 'टैप',
      'sos_button_accessibility_label': 'आपातकालीन SOS बटन',
      'sos_button_accessibility_hint': 'नज़दीकी रिस्पॉन्डर्स को अलर्ट करने के लिए टैप करें। लंबा दबाने पर रद्द करें।',
      'profile_this_is_your_view': 'यह आपका रिस्पॉन्डर प्रोफ़ाइल दृश्य है।',
      'profile_call': 'कॉल',
      'profile_message': 'संदेश',
      'profile_community_reviews': 'समुदाय समीक्षा',
      'profile_rate_review': 'रेट करें और समीक्षा करें',
      'profile_no_reviews_yet': 'अभी तक कोई समीक्षा नहीं। अपना अनुभव साझा करने वाला पहला बनें!',
      'profile_edit_delete': 'संपादित करें/हटाएं',
      'profile_no_phone_number': 'इस रिस्पॉन्डर के लिए कोई फोन नंबर उपलब्ध नहीं है।',
      'profile_could_not_open_dialer': 'इस डिवाइस पर डायलर खोलने में असमर्थ।',
      'profile_no_messaging_number': 'इस रिस्पॉन्डर के लिए कोई मैसेजिंग नंबर उपलब्ध नहीं है।',
      'profile_messaging_not_supported': 'यह डिवाइस अभी संदेश भेजने का समर्थन नहीं करता है।',
      'profile_review_title': 'समीक्षा {name}',
      'profile_give_rating_review': 'एक रेटिंग और समीक्षा दोनों दें।',
      'profile_share_experience': 'इस रिस्पॉन्डर के साथ अपना अनुभव साझा करें...',
      'profile_unable_delete_review': 'समीक्षा हटाने में असमर्थ: ',
      'profile_review_deleted': 'समीक्षा हटाई गई।',
      'profile_cancel': 'रद्द करें',
      'profile_unable_save_review': 'समीक्षा सहेजने में असमर्थ: ',
      'profile_review_saved': 'समीक्षा सहेजी गई।',
      'profile_save_review': 'समीक्षा सहेजें',
      'responder_skill_medical_emergency': 'मेडिकल इमरजेंसी',
      'responder_skill_fire_and_rescue': 'फायर और रेस्क्यू',
      'responder_skill_search_and_rescue': 'खोज और रेस्क्यू',
      'responder_skill_shelter_and_evacuation': 'आश्रय और निकासी',
      'responder_skill_food_and_water_supply': 'भोजन और पानी की आपूर्ति',
      'responder_skill_elderly_assist': 'वृद्ध लोगों की सहायता',
      'responder_skill_women_safety': 'महिला सुरक्षा',
      'responder_skill_child_safety': 'बच्चों की सुरक्षा',
      'responder_skill_essential_medicines': 'आवश्यक दवाइयां',
      'responder_skill_mobility_support': 'गतिशीलता सहायता',
      'responder_skill_communication_relay': 'संचार रिले',
      'responder_skill_logistics_and_transport': 'लॉजिस्टिक्स और परिवहन',
      'responder_skill_general_support': 'सामान्य समर्थन',
      'responder_type_community_volunteer': 'समुदाय स्वयंसेवक',
      'responder_type_medical_professional': 'चिकित्सा पेशेवर',
      'responder_type_firefighter': 'दमकलकर्मी',
      'responder_type_police': 'पुलिस',
      'responder_type_off_duty_authority': 'ऑफ-ड्यूटी अधिकारी',
      'responder_type_civil_defense': 'नागरिक रक्षा',
      'responder_type_ngo_worker': 'एनजीओ कार्यकर्ता',
      'responder_type_logistics_provider': 'लॉजिस्टिक्स प्रदाता',
      'responder_type_shelter_host': 'आश्रय होस्ट',
      'status_no_sos_chats_found': 'अभी कोई SOS चैट नहीं मिली।',
      'status_no_open_requests': 'अभी कोई खुली रिक्वेस्ट नहीं है।',
      'status_no_matching_requests': 'आपके पास अभी कोई मिलती-जुलती रिक्वेस्ट नहीं है।',
      'filter_all_active': 'सभी सक्रिय',
      'filter_joined_by_me': 'मेरे द्वारा शामिल',
      'view_details_and_media': 'विवरण और मीडिया देखें',
      'reporter_message': 'रिपोर्टर संदेश:',
      'voice_transcript': 'वॉइस ट्रांसक्रिप्ट:',
      'open_image': 'छवि खोलें',
      'open_external': 'बाहरी रूप से खोलें',
      'play_audio': 'ऑडियो चलाएं',
      'stop_audio': 'ऑडियो रोकें',
      'navigate': 'नेविगेट करें',
      'image_unavailable_preview': 'पूर्वावलोकन में छवि उपलब्ध नहीं है। छवि खोलें का उपयोग करें।',
      'no_nearby_responders_hint': 'अभी पास में कोई प्रतिक्रिया कर्ता नहीं है। आपातकालीन कॉल/SMS को बैकअप के रूप में इस्तेमाल करें।',
      'analysis_results': 'विश्लेषण परिणाम',
      'category_label': 'श्रेणी',
      'severity_label': 'गंभीरता',
      'skill_match': 'कौशल मिलान',
      'manual_override_critical': 'मैनुअल ओवरराइड: अत्यंत गंभीर',
      'human_review_recommended': 'मानवीय समीक्षा की सलाह दी जाती है',
      'recommended_actions': 'अनुशंसित कार्य',
      'offline_mode_active': 'ऑफ़लाइन मोड (AI फ़ॉलबैक सक्रिय)',
      'category_fire_emergency': 'आग आपातकाल',
      'category_medical_emergency': 'चिकित्सा आपातकाल',
      'category_disaster_evacuation': 'आपदा निकासी',
      'category_essential_supply_need': 'आवश्यक आपूर्ति की आवश्यकता',
      'category_elderly_assistance': 'वृद्ध सहायता',
      'category_women_safety': 'महिला सुरक्षा',
      'category_child_safety': 'बाल सुरक्षा',
      'category_search_and_rescue': 'खोज एवं बचाव',
      'category_water_rescue_emergency': 'जल बचाव आपातकाल',
      'category_railway_hazard_emergency': 'रेलवे खतरा आपातकाल',
      'category_entrapment_rescue': 'फँसाव बचाव',
      'category_animal_insect_attack': 'जानवर/कीट हमला',
      'category_general_emergency': 'सामान्य आपातकाल',
      'category_medical_safety_emergency': 'चिकित्सा सुरक्षा आपातकाल',
      'category_rescue_emergency': 'बचाव आपातकाल',
      'skill_fire_rescue': 'आग एवं बचाव',
      'skill_medical_emergency': 'चिकित्सा आपातकाल',
      'skill_search_rescue': 'खोज एवं बचाव',
      'skill_shelter_evacuation': 'आश्रय एवं निकासी',
      'skill_food_water_supply': 'भोजन एवं जल आपूर्ति',
      'skill_elderly_assist': 'वृद्ध सहायता',
      'skill_women_safety': 'महिला सुरक्षा',
      'skill_child_safety': 'बाल सुरक्षा',
      'skill_general_support': 'सामान्य सहायता',
      'sos_default_message': 'संभावित आपात स्थिति को तुरंत सहायता चाहिए।',
      'chat_group_title': 'RescueLink समूह चैट',
      'chat_online_count': '{count} ऑनलाइन',
      'chat_sos_cancelled': 'यह SOS रद्द कर दिया गया है।',
      'chat_failed_load_messages': 'संदेश लोड नहीं हो सके',
      'chat_no_messages_yet': 'अभी कोई संदेश नहीं है। बातचीत शुरू करें।',
      'chat_ask_ai_assistant': 'AI सहायक से पूछें',
      'chat_actions_tooltip': 'चैट विकल्प',
      'chat_view_responders': 'प्रतिक्रिया कर्ता देखें',
      'chat_delete_chat_victim': 'चैट हटाएं (पीड़ित)',
      'chat_leave_chat_responder': 'चैट छोड़ें (प्रतिक्रिया कर्ता)',
      'chat_active_responders': 'सक्रिय प्रतिक्रियाशील ({count})',
      'button_responder_dashboard': 'प्रतिक्रिया कर्ता डैशबोर्ड',
      'label_emergency_details_optional': 'आपातकालीन विवरण (वैकल्पिक)',
      'hint_emergency_details_example': 'उदाहरण: वृद्ध व्यक्ति गिरा, बाढ़ नजदीक, बच्चा गुम, कोई परिवहन नहीं',
      'tooltip_voice_to_text': 'वॉइस से टेक्स्ट',
      'tooltip_stop_voice_to_text': 'वॉइस टू टेक्स्ट रोकें',
      'tooltip_record_voice_clip': 'वॉइस क्लिप रिकॉर्ड करें',
      'tooltip_stop_voice_clip': 'वॉइस क्लिप रोकें',
      'tooltip_play_preview': 'पूर्वावलोकन चलाएं',
      'tooltip_stop_preview': 'पूर्वावलोकन रोकें',
      'tooltip_capture_photo': 'फ़ोटो कैप्चर करें',
      'attachment_photo': 'फ़ोटो अटैचमेंट',
      'semantics_view_attached_photo': 'संलग्न फ़ोटो देखें',
      'attachment_voice': 'वॉइस अटैचमेंट',
      'semantics_play_attached_voice_clip': 'संग्लन वॉइस क्लिप चलाएँ',
      'status_visual_ai_disabled': 'दृश्य AI अक्षम (स्थानीय फॉलबैक)',
      'status_visual_ai_enabled': 'दृश्य AI सक्षम (Gemini मल्टीमोडल)',
      'status_transcription_cloud_enabled': 'ट्रांसक्रिप्शन: क्लाउड सहायक सक्षम',
      'status_transcription_ondevice_free': 'ट्रांसक्रिप्शन: केवल ऑन-डिवाइस (मुफ्त मोड)',
      'status_transcript_ready': 'ट्रांसक्रिप्ट तैयार',
      'status_transcript_percent': 'ट्रांसक्रिप्ट {pct}%',
      'status_local_fallback': 'स्थानीय फॉलबैक',
      'chat_emergency_overview': 'आपातकालीन अवलोकन',
      'home_select_language': 'भाषा चुनें',
      'home_choose_preferred_language': 'अपनी पसंदीदा भाषा चुनें',
      'account_anonymous_session': 'गुमनाम सत्र',
      'account_registered_account': 'पंजीकृत खाता',
      'account_signin_create': 'साइन इन / खाता बनाएं',
      'responder_deregister': 'प्रतिक्रिया कर्ता पंजीकरण हटाएं',
      'accessibility_announcement_text': 'एक्सेसिबिलिटी परीक्षण घोषणा। SOS बटन जानकारी कार्ड के नीचे केंद्र में है।',
      'accessibility_announcement_sent': 'स्क्रीन रीडर घोषणा भेज दी गई।',
      'flash_test_completed': 'फ्लैश परीक्षण पूरा हुआ।',
      'notification_permission_not_granted': 'नोटिफिकेशन अनुमति नहीं मिली।',
      'comms_simulation_title': 'कनेक्टिविटी सिमुलेशन',
      'comms_simulate_tower_failure': 'टावर विफलता सिमुलेट करें',
      'comms_device_supports_satellite': 'डिवाइस सैटेलाइट समर्थन',
      'comms_simulated_capability': 'सिमुलेटेड क्षमता',
      'comms_simulation_info': 'यह सिमुलेशन बिना वास्तविक mesh या satellite हार्डवेयर के आपदा/लॉकडाउन कनेक्टिविटी फॉलबैक का परीक्षण करने देता है।',
      'label_route': 'रूट',
      'comms_mode_auto': 'ऑटो',
      'comms_mode_internet': 'इंटरनेट',
      'comms_mode_mesh_simulated': 'मेश (नकली)',
      'comms_mode_satellite_simulated': 'सैटेलाइट (नकली)',
      'comms_route_internet': 'इंटरनेट रूट',
      'comms_route_mesh_simulated': 'मेश रिले (नकली)',
      'comms_route_satellite_simulated': 'सैटेलाइट अपलिंक (नकली)',
      'label_case_id': 'केस आईडी',
      'status_cancelled': 'रद्द किया गया',
      'dialog_delete_cancelled_chat_title': 'रद्द की गई चैट हटाएं?',
      'dialog_delete_cancelled_chat_body': 'यह स्थायी रूप से इस रद्द SOS चैट और सभी संदेशों को डेटाबेस से हटा देता है।',
      'button_keep': 'रखें',
      'button_delete': 'हटाएं',
      'tooltip_delete_cancelled_chat': 'रद्द की गई चैट हटाएं',
      'snackbar_cancelled_chat_deleted': 'रद्द की गई चैट हटाई गई।',
      'snackbar_failed_delete_chat': 'चैट हटाने में विफल। कृपया पुनः प्रयास करें।',
      'dialog_leave_conversation_title': 'क्या आप इस बातचीत को छोड़ना चाहते हैं?',
      'dialog_leave_conversation_body': 'यदि आप छोड़ते हैं, तो बाद में फिर से शामिल होने के लिए अनुमति की आवश्यकता होगी।',
      'button_leave': 'छोड़ें',
      'snackbar_conversation_removed': 'बातचीत आपकी सूची से निकाल दी गई है।',
      'button_cancel': 'रद्द करें',
      'status_no_active_chats': 'अभी कोई सक्रिय चैट नहीं है।',
      'status_no_joined_chats': 'आपने अभी तक कोई चैट जॉइन नहीं की है।',
      'status_no_matching_chats': 'आपकी खोज से कोई चैट मेल नहीं खाती।',
      'responder_chat_showing_joined': '{total} चैट दिख रही हैं • जॉइन {joined}',
      'responder_chat_tap_hint': 'बातचीत खोलने के लिए चैट पर टैप करें। जरूरत होने पर जॉइन चैट के अंदर होगा।',
      'status_no_sos_message_available': 'कोई SOS संदेश उपलब्ध नहीं',
    },
    'ta': {
      'app_title': 'மீட்பு இணைப்பு',
      'emergency_prompt': 'அவசரநிலையா?',
      'emergency_subtitle': 'அருகிலுள்ள பதிலளிப்போருக்கு எச்சரிக்க கீழே உள்ள SOS பொத்தானை அழுத்தவும்',
      'become_responder': 'பதிலளிப்பவராக சேரவும்',
      'location_ready': 'இடம்: தயாராக உள்ளது',
      'location_not_ready': 'இடம்: தயாரில்லை',
      'user_info': 'பயனர் தகவல்',
      'total_responders': 'மொத்த பதிலளிப்பவர்கள்',
      'nearby_5km': 'அருகில் (5 கிமீ)',
      'sign_in_title': 'RescueLink உள்நுழைவு',
      'sign_in': 'உள்நுழை',
      'create_account': 'கணக்கு உருவாக்கு',
      'language': 'மொழி',
      'continue_guest': 'விருந்தினராக தொடரவும்',
      // Button labels
      'button_cancel_sos': 'SOS ரத்து செய்யவும்',
      'button_view_map': 'வரைபடத்தைக் காட்டவும்',
      'button_open_chat': 'சேட் திறக்கவும்',
      'button_call_emergency': '112 க்கு அழைக்கவும்',
      'button_sign_out': 'வெளியேறவும்',
      'button_people_needing_help': 'உதவி தேவைப்பட்டவர்கள்',
      'button_voice_test': 'குரல் சோதனை',
      'button_flash_test': 'ஃபிளாஷ் சோதனை',
      'button_responder_register': 'பதிலளிப்பவராக பதிவுசெய்யவும்',
      'button_accept': 'ஏற்றுக்கொள்ளவும்',
      'button_reject': 'நிராகரிக்கவும்',
      // Screen titles
      'title_my_sos_chats': 'என் SOS சேட்',
      'title_responder_alerts': 'பதிலளிப்பவர் எச்சரிக்கைகள்',
      'title_map': 'அவசரநிலை வரைபடம்',
      'title_profile': 'சுயவிவரம்',
      'title_settings': 'அமைப்புகள்',
      'title_accessibility': 'அணுகல் அமைப்புகள்',
      // Filter chips
      'filter_active': 'செயல்பாடு',
      'filter_cancelled': 'ரத்து செய்யப்பட்டது',
      'filter_all': 'அனைத்தும்',
      // Search & input hints
      'hint_search_case': 'வழக்கு ID அல்லது செய்தி மூலம் தேடவும்',
      'hint_emergency_context': 'அவசரநிலை சூழ்நிலையை விவரிக்கவும்',
      'chat_type_message': 'ஒரு செய்தியை টাইப் செய்க',
      // Labels
      'label_text_size': 'உரை அளவு',
      'label_haptics': 'ஆபிரக்ஸ் கருத்தோம்',
      'label_high_contrast': 'அதிக வேறுபாட்டு முறை',
      'label_flashlight': 'பிளாஷ் விளக்கு',
      'label_flashlight_hint': 'உதவிக்காக சிக்னல் அனுப்ப அல்லது உங்கள் பாதையை வெளிச்சப்படுத்த சாதன விளக்கை பயன்படுத்தவும்.',
      'label_notifications_hint': 'பக்கமுள்ள பதிலளிப்பவர்கள் மற்றும் வழக்கு புதுப்பிப்புகளுக்கான அறிவிப்புகளை பெறுங்கள்.',
      'button_reset': 'மீட்டமை',
      'label_notifications': 'அறிவிப்புகள்',
      'label_nearby_responders': 'அருகிலுள்ள பதிலளிப்பவர்கள்',
      'label_responder_online': 'பதிலளிப்பவர் ஆன்லைன்',
      // Status & Messages
      'status_sos_received': '✓ SOS பெறப்பட்டது',
      'status_requesting_location': 'உங்கள் இடத்தைக் கேட்கிறது...',
      'status_no_location': 'இடத்தை தீர்மானிக்க முடியவில்லை. மீண்டும் முயற்சி செய்யவும்.',
      'status_please_sign_in': 'சேட்களைக் காண கடந்தாக உள்நுழையவும்.',
      'status_chat_not_ready': 'சேட் இன்னும் தயாரில்லை.',
      'status_not_signed_in': 'உள்நுழையவில்லை',
      'status_location_ready': 'இடம் தயாரக உள்ளது',
      'status_location_not_ready': 'இடம் தயாரில்லை',
      'status_sos_activated': 'SOS செயல்படுத்தப்பட்டது. அருகிலுள்ள பதிலளிப்பவர்கள் உத்தரவிட்டனர்.',
      'status_sos_photo_upload_failed': 'புகைப்படம் பதிவேற்ற தோல்வி: ',
      'status_sos_audio_failed': 'ஆடியோ இணைப்பு தோல்வி: ',
      'status_sos_setup_refreshed': 'சேட் அமைப்பு புதுப்பிக்கப்பட்டது. இப்போது நீங்கள் அனுப்ப முயற்சி செய்யலாம்.',
      // Error messages
      'error_chat_setup_failed': 'சேட் அமைப்பு தோல்வி. மீண்டும் முயற்சி செய்யவும்.',
      'error_sos_incomplete': 'SOS முடிக்க முடியவில்லை. மீண்டும் முயற்சி செய்யவும்.',
      'error_failed_load_chats': 'சேட்களைப் பதிவேற்ற விफலமாக இருந்தது',
      // Dialog & confirmation
      'dialog_sos_confirmation': 'SOS ट्रिगर செய்யப்பட்டது',
      'dialog_attachment_photo': 'புகைப்படம் இணைக்கப்பட்டது',
      'dialog_attachment_voice': 'குரல் கிளிப் இணைக்கப்பட்டது',
      'dialog_sent_attachment': 'இணைப்பு அனுப்பப்பட்டது',
      // Menu items
      'menu_disable_notifications': 'இந்த சேட்க்கான அறிவிப்புகளை முடக்கவும்',
      'menu_enable_notifications': 'இந்த சேட்க்கான அறிவிப்புகளை இயக்கவும்',
      'menu_delete_chat': 'சேட்டைத் திரைக்கவும்',
      'menu_mute': 'மவுத் செய்யவும்',
      'menu_unmute': 'மவுத் நீக்கவும்',
      'button_force_critical': 'முக்கிய செயலை வலுப்படுத்து',
      'button_powered_by_gemini': 'Gemini மூலம் இயங்குகிறது',
      'button_select_document': 'ஆவணத்தைத் தேர்ந்தெடுக்கவும்',
      'button_upload': 'அப்லோடு',
      'label_id_upload': 'அடையாள ஆவணம் பதிவேற்றம் (விருப்பமானது)',
      'responder_registration_id_description': 'உறுதிப்படுத்தலுக்காக உங்கள் அதிகாரபூர்வ அடையாளத்தை (பாஸ்போர்ட், ஓட்டுநர் உரிமம், அல்லது தேசிய அடையாளம்) பதிவேற்றவும். ஏற்றுக்கொள்ளப்பட்ட கோப்பு வடிவுகள்: PDF, JPG, PNG',
      'document_uploaded_successfully': 'ஆவணம் வெற்றிகரமாக பதிவேற்றப்பட்டது',
      'label_document_name': 'அடையாள ஆவணம்',
      'status_uploading': 'பதிவேற்றம் ஆகிறது...',
      'prompt_select_document_first': 'முதலில் ஒரு ஆவணத்தைத் தேர்ந்தெடுக்கவும்',
      'prompt_sign_in_first': 'முதலில் உள்நுழையவும்',
      'error_document_upload_failed': 'ஆவணம் பதிவேற்றப்படவில்லை: {error}',
      'sos_button_label': 'SOS',
      'sos_button_tap': 'தொடவும்',
      'sos_button_accessibility_label': 'அவசர SOS பொத்தான்',
      'sos_button_accessibility_hint': 'அருகிலுள்ள பதிலளிப்போருக்கு எச்சரிக்க தொடவும். நீண்ட அழுத்தத்தில் ரத்து செய்யவும்.',
      'profile_this_is_your_view': 'இது உங்கள் பதிலளிப்பவர் சுயவிவர காட்சி.',
      'profile_call': 'அழைப்பு',
      'profile_message': 'செய்தி',
      'profile_community_reviews': 'சமுதாய விமர்சனங்கள்',
      'profile_rate_review': 'மதிப்பீடு & விமர்சனம்',
      'profile_no_reviews_yet': 'இன்னும் எந்த விமர்சனமும் இல்லை. உங்கள் அனுபவத்தை பகிர்வதில் முதலாவது இருங்கள்!',
      'profile_edit_delete': 'மாற்று/நீக்கு',
      'profile_no_phone_number': 'இந்த பதிலளிப்பவருக்கான தொலைபேசி எண் கிடைக்கவில்லை.',
      'profile_could_not_open_dialer': 'இந்த சாதனத்தில் டயலரைத் திறக்க முடியவில்லை.',
      'profile_no_messaging_number': 'இந்த பதிலளிப்பவருக்கான செய்தி எண் கிடைக்கவில்லை.',
      'profile_messaging_not_supported': 'இந்த சாதனம் இப்போது செய்தி அனுப்ப ஆதரிக்காது.',
      'profile_review_title': '{name} ஐப் பற்றிய மதிப்பீடு',
      'profile_give_rating_review': 'மதிப்பீடு மற்றும் விமர்சனத்தை இரண்டையும் வழங்கவும்.',
      'profile_share_experience': 'இந்த பதிலளிப்பவருடன் உங்கள் அனுபவத்தைப் பகிரவும்...',
      'profile_unable_delete_review': 'விமர்சனத்தை நீக்க முடியவில்லை: ',
      'profile_review_deleted': 'விமர்சனம் நீக்கப்பட்டது.',
      'profile_cancel': 'ரத்து செய்',
      'profile_unable_save_review': 'விமர்சனத்தைச் சேமிக்க முடியவில்லை: ',
      'profile_review_saved': 'விமர்சனம் சேமிக்கப்பட்டது.',
      'profile_save_review': 'விமர்சனத்தைச் சேமி',
      'responder_skill_medical_emergency': 'மருத்துவ அவசரநிலை',
      'responder_skill_fire_and_rescue': 'தீ & மீட்பு',
      'responder_skill_search_and_rescue': 'தேடு மற்றும் மீட்பு',
      'responder_skill_shelter_and_evacuation': 'சேவல் மற்றும் வெளியேற்றம்',
      'responder_skill_food_and_water_supply': 'உணவு மற்றும் தண்ணீர் வழங்கல்',
      'responder_skill_elderly_assist': 'முதிர்வோர் உதவி',
      'responder_skill_women_safety': 'பெண் பாதுகாப்பு',
      'responder_skill_child_safety': 'குழந்தை பாதுகாப்பு',
      'responder_skill_essential_medicines': 'அத்தியாவசிய மருந்துகள்',
      'responder_skill_mobility_support': 'சுற்றுச்சூழல் ஆதரவு',
      'responder_skill_communication_relay': 'தொடர்பு ரிலை',
      'responder_skill_logistics_and_transport': 'லாஜிஸ்டிக்ஸ் மற்றும் போக்குவரத்து',
      'responder_skill_general_support': 'பொது ஆதரவு',
      'responder_type_community_volunteer': 'சமுதாய தன்னார்வலர்',
      'responder_type_medical_professional': 'மருத்துவ நிபுணர்',
      'responder_type_firefighter': 'தீயணைப்பு வீரர்',
      'responder_type_police': 'போலீஸ்',
      'responder_type_off_duty_authority': 'கடமையில் இல்லாத அதிகாரி',
      'responder_type_civil_defense': 'சிவில் பாதுகாப்பு',
      'responder_type_ngo_worker': 'என்ஜிஓ பணியாளர்',
      'responder_type_logistics_provider': 'லாஜிஸ்டிக்ஸ் வழங்குநர்',
      'responder_type_shelter_host': 'சேவல் ஹோஸ்ட்',
      'status_no_sos_chats_found': 'இன்னும் SOS சேட்கள் இல்லை.',
      'status_no_open_requests': 'தற்போது திறந்த கோரிக்கைகள் இல்லை.',
      'status_no_matching_requests': 'உங்களுக்குப் பொருந்தும் கோரிக்கைகள் இல்லை.',
      'filter_all_active': 'அனைத்து செயல்பாடுகள்',
      'filter_joined_by_me': 'நான் சேர்ந்தவை',
      'view_details_and_media': 'விவரங்கள் மற்றும் ஊடகத்தைப் பார்க்கவும்',
      'reporter_message': 'அறிவிப்பவர் செய்தி:',
      'voice_transcript': 'குரல் உரை:',
      'open_image': 'படத்தைத் திறக்கவும்',
      'open_external': 'வெளிப்புறமாக திறக்கவும்',
      'play_audio': 'ஒலியை இயக்கவும்',
      'stop_audio': 'ஒலியை நிறுத்தவும்',
      'navigate': 'வழிசெலுத்து',
      'image_unavailable_preview': 'முன்னோட்டத்தில் படம் இல்லை. Open image ஐ பயன்படுத்தவும்.',
      'no_nearby_responders_hint': 'அருகில் பதிலளிப்பவர்கள் இல்லை. அவசர அழைப்பு/SMS ஐ காப்பு விருப்பமாக பயன்படுத்தவும்.',
      'analysis_results': 'பகுப்பாய்வு முடிவுகள்',
      'category_label': 'வகை',
      'severity_label': 'கடுமை',
      'skill_match': 'திறன் பொருத்தம்',
      'manual_override_critical': 'கைமுறை மேலெழுத்து: மிகக் கடுமை',
      'human_review_recommended': 'மனித ஆய்வு பரிந்துரைக்கப்படுகிறது',
      'recommended_actions': 'பரிந்துரைக்கப்பட்ட செயல்கள்',
      'offline_mode_active': 'ஆஃப்லைன் முறை (AI மாற்று செயல்பாடு)',
      'category_fire_emergency': 'தீ அவசரநிலை',
      'category_medical_emergency': 'மருத்துவ அவசரநிலை',
      'category_disaster_evacuation': 'பேரிடர் வெளியேற்றம்',
      'category_essential_supply_need': 'அத்தியாவசிய பொருள் தேவை',
      'category_elderly_assistance': 'முதியோர் உதவி',
      'category_women_safety': 'பெண்கள் பாதுகாப்பு',
      'category_child_safety': 'குழந்தை பாதுகாப்பு',
      'category_search_and_rescue': 'தேடல் மற்றும் மீட்பு',
      'category_water_rescue_emergency': 'நீர் மீட்பு அவசரநிலை',
      'category_railway_hazard_emergency': 'ரயில்வே அபாய அவசரநிலை',
      'category_entrapment_rescue': 'சிக்கல் மீட்பு',
      'category_animal_insect_attack': 'விலங்கு/பூச்சி தாக்குதல்',
      'category_general_emergency': 'பொது அவசரநிலை',
      'category_medical_safety_emergency': 'மருத்துவ பாதுகாப்பு அவசரநிலை',
      'category_rescue_emergency': 'மீட்பு அவசரநிலை',
      'skill_fire_rescue': 'தீ & மீட்பு',
      'skill_medical_emergency': 'மருத்துவ அவசரநிலை',
      'skill_search_rescue': 'தேடல் & மீட்பு',
      'skill_shelter_evacuation': 'தங்குமிடம் & வெளியேற்றம்',
      'skill_food_water_supply': 'உணவு & நீர் வழங்கல்',
      'skill_elderly_assist': 'முதியோர் உதவி',
      'skill_women_safety': 'பெண்கள் பாதுகாப்பு',
      'skill_child_safety': 'குழந்தை பாதுகாப்பு',
      'skill_general_support': 'பொது உதவி',
      'sos_default_message': 'சாத்தியமான அவசரநிலைக்கு உடனடி உதவி தேவை.',
      'chat_group_title': 'மீட்பு இணைப்பு குழு அரட்டை',
      'chat_online_count': '{count} ஆன்லைன்',
      'chat_sos_cancelled': 'இந்த SOS ரத்து செய்யப்பட்டது.',
      'chat_failed_load_messages': 'செய்திகளை ஏற்ற முடியவில்லை',
      'chat_no_messages_yet': 'இன்னும் செய்தி இல்லை. உரையாடலை தொடங்குங்கள்.',
      'chat_ask_ai_assistant': 'AI உதவியாளரை கேளுங்கள்',
      'chat_actions_tooltip': 'அரட்டை செயல்கள்',
      'chat_view_responders': 'பதிலளிப்பவர்களை காண்க',
      'chat_delete_chat_victim': 'அரட்டை நீக்கு (பாதிக்கப்பட்டவர்)',
      'chat_leave_chat_responder': 'அரட்டையை விட்டு வெளியேறு (பதிலளிப்பவர்)',
      'chat_active_responders': 'செயலில் உள்ள பதிலளிப்பவர்கள் ({count})',
      'button_responder_dashboard': 'பதிலளிப்பவர் டாஷ்போர்டு',
      'label_emergency_details_optional': 'அவசர விவரங்கள் (விருப்பத் தெரிவு)',
      'hint_emergency_details_example': 'உதாரணம்: முதியவர் விழுந்தார், πλημμύρα அருகே, குழந்தை காணவில்லை, போக்குவரத்து இல்லை',
      'tooltip_voice_to_text': 'ஒலி உரைக்கு',
      'tooltip_stop_voice_to_text': 'ஒலி உரையை நிறுத்து',
      'tooltip_record_voice_clip': 'ஒலி கிளிப் பதிவு செய்',
      'tooltip_stop_voice_clip': 'ஒலி கிளிப்பை நிறுத்து',
      'tooltip_play_preview': 'முன்நோட்டத்தை இயக்கு',
      'tooltip_stop_preview': 'முன்நோட்டத்தை நிறுத்து',
      'tooltip_capture_photo': 'புகைப்படத்தை பிடி',
      'attachment_photo': 'புகைப்பட இணைப்பு',
      'semantics_view_attached_photo': 'இணைக்கப்பட்ட புகைப்படத்தை பார்க்கவும்',
      'attachment_voice': 'ஒலி இணைப்பு',
      'semantics_play_attached_voice_clip': 'இணைக்கப்பட்ட ஒலி கிளிப்பை இயக்கவும்',
      'status_visual_ai_disabled': 'காட்சி AI அணைக்கப்பட்டது (உள்ளூர் ஃபார்பேக்)',
      'status_visual_ai_enabled': 'காட்சி AI இயல்பில் உள்ளது (Gemini மல்டிமோடல்)',
      'status_transcription_cloud_enabled': 'உரைமொழிபெயர்ப்பு: மேக உதவி இயல்பு உள்ளது',
      'status_transcription_ondevice_free': 'உரைமொழிபெயர்ப்பு: சாதனத்தில் மட்டுமே (இலவச முறை)',
      'status_transcript_ready': 'உரைமொழிபெயர்ப்பு தயார்',
      'status_transcript_percent': 'உரைமொழிபெயர்ப்பு {pct}%',
      'status_local_fallback': 'உள்ளூர் ஃபார்பேக்',
      'chat_emergency_overview': 'அவசர நிலை சுருக்கம்',
      'home_select_language': 'மொழியை தேர்வு செய்க',
      'home_choose_preferred_language': 'உங்கள் விருப்ப மொழியை தேர்வு செய்க',
      'account_anonymous_session': 'அடையாளமற்ற அமர்வு',
      'account_registered_account': 'பதிவு செய்யப்பட்ட கணக்கு',
      'account_signin_create': 'உள்நுழை / கணக்கு உருவாக்கு',
      'responder_deregister': 'பதிலளிப்பவர் பதிவு நீக்கு',
      'accessibility_announcement_text': 'அணுகல் சோதனை அறிவிப்பு. SOS பொத்தான் தகவல் அட்டைகளின் கீழ் மையத்தில் உள்ளது.',
      'accessibility_announcement_sent': 'ஸ்கிரீன் ரீடர் அறிவிப்பு அனுப்பப்பட்டது.',
      'flash_test_completed': 'ஃப்ளாஷ் சோதனை முடிந்தது.',
      'notification_permission_not_granted': 'அறிவிப்பு அனுமதி வழங்கப்படவில்லை.',
      'comms_simulation_title': 'தொடர்பு மாதிரியாக்கம்',
      'comms_simulate_tower_failure': 'டவர் செயலிழப்பை மாதிரியாக்கு',
      'comms_device_supports_satellite': 'சாதனம் செயற்கைக்கோளை ஆதரிக்கிறது',
      'comms_simulated_capability': 'மாதிரி திறன்',
      'comms_simulation_info': 'இந்த மாதிரியாக்கம் உண்மையான mesh அல்லது satellite வன்பொருள் இன்றி பேரிடர்/தடைநிலை இணைப்பு fallback ஐ சோதிக்க உதவும்.',
      'label_route': 'பாதை',
      'comms_mode_auto': 'தானாக',
      'comms_mode_internet': 'இணையம்',
      'comms_mode_mesh_simulated': 'மேஷ் (உள்ளடக்கியது)',
      'comms_mode_satellite_simulated': 'சாடலைட் (உள்ளடக்கியது)',
      'comms_route_internet': 'இணைய பாதை',
      'comms_route_mesh_simulated': 'மேஷ் ரிலே (உள்ளடக்கியது)',
      'comms_route_satellite_simulated': 'சாடலைட் அப்பிலிங்க் (உள்ளடக்கியது)',
      'label_case_id': 'வழக்கு ID',
      'status_cancelled': 'ரத்து செய்யப்பட்டது',
      'dialog_delete_cancelled_chat_title': 'ரத்து செய்யப்பட்ட அரட்டை நீக்கவா?',
      'dialog_delete_cancelled_chat_body': 'இந்த அரட்டை மற்றும் அனைத்து செய்திகளையும் தரவுத்தளத்திலிருந்து நிரந்தரமாக நீக்குகிறது.',
      'button_keep': 'தாங்கவும்',
      'button_delete': 'நீக்கு',
      'tooltip_delete_cancelled_chat': 'ரத்து செய்யப்பட்ட அரட்டை நீக்கவும்',
      'snackbar_cancelled_chat_deleted': 'ரத்து செய்யப்பட்ட அரட்டை நீக்கப்பட்டது.',
      'snackbar_failed_delete_chat': 'அரட்டை நீக்க முடியவில்லை. மீண்டும் முயற்சி செய்க.',
      'dialog_leave_conversation_title': 'இந்த உரையாடலை விட்டு வெளியேறவா?',
      'dialog_leave_conversation_body': 'நீங்கள் வெளியேறினால் பின்னர் மீண்டும் சேர அனுமதி தேவைப்படும்.',
      'button_leave': 'விடு',
      'snackbar_conversation_removed': 'உரையாடல் உங்கள் பட்டியலிலிருந்து நீக்கப்பட்டது.',
      'button_cancel': 'ரத்து செய்',
      'status_no_active_chats': 'இப்போது செயலிலுள்ள அரட்டைகள் இல்லை.',
      'status_no_joined_chats': 'நீங்கள் இன்னும் எந்த அரட்டையிலும் சேரவில்லை.',
      'status_no_matching_chats': 'உங்கள் தேடலுக்கு ஏற்ற அரட்டைகள் இல்லை.',
      'responder_chat_showing_joined': '{total} அரட்டைகள் • சேர்ந்தவை {joined}',
      'responder_chat_tap_hint': 'உரையாடலைத் திறக்க அரட்டையைத் தொடவும். தேவைப்பட்டால் சேர்வு அரட்டையின் உள்ளே நடக்கும்.',
      'status_no_sos_message_available': 'SOS செய்தி இல்லை',
    },
    'te': {
      'app_title': 'RescueLink',
      'emergency_prompt': 'In an Emergency?',
      'emergency_subtitle': 'Press the SOS button below to alert nearby responders',
      'become_responder': 'Become A Responder',
      'location_ready': 'Location: Ready',
      'location_not_ready': 'Location: Not Ready',
      'user_info': 'User Info',
      'total_responders': 'Total Responders',
      'nearby_5km': 'Nearby (5km)',
      'sign_in_title': 'RescueLink సైన్ ఇన్',
      'sign_in': 'Sign In',
      'create_account': 'Create Account',
      'continue_guest': 'గెస్ట్‌గా కొనసాగండి',
      'language': 'భాష',
      'button_cancel_sos': 'Cancel SOS',
      'button_view_map': 'View Map',
      'button_open_chat': 'Open Chat',
      'button_call_emergency': 'Call 112',
      'button_sign_out': 'Sign Out',
      'button_people_needing_help': 'People Needing Help',
      'button_voice_test': 'Voice Test',
      'button_flash_test': 'Flash Test',
      'button_responder_register': 'Register as Responder',
      'button_accept': 'Accept',
      'button_reject': 'Reject',
      'title_my_sos_chats': 'My SOS Chats',
      'title_responder_alerts': 'Responder Alerts',
      'title_map': 'Emergency Map',
      'title_profile': 'Profile',
      'title_settings': 'Settings',
      'title_accessibility': 'Accessibility Settings',
      'filter_active': 'Active',
      'filter_cancelled': 'Cancelled',
      'filter_all': 'All',
      'hint_search_case': 'Search by case ID or message',
      'hint_emergency_context': 'Describe emergency situation',
      'label_text_size': 'Text Size',
      'label_haptics': 'Haptics',
      'label_high_contrast': 'High Contrast Mode',
      'label_notifications': 'Notifications',
      'label_nearby_responders': 'Nearby Responders',
      'label_responder_online': 'Responder Online',
      'status_sos_received': '✓ SOS Received',
      'status_requesting_location': 'Requesting your location...',
      'status_no_location': 'Unable to determine location. Please try again.',
      'status_please_sign_in': 'Please sign in to view chats.',
      'status_chat_not_ready': 'Chat is not ready yet.',
      'status_not_signed_in': 'Not signed in',
      'status_location_ready': 'Location Ready',
      'status_location_not_ready': 'Location Not Ready',
      'status_sos_activated': 'SOS activated. Nearby responders have been notified.',
      'status_sos_photo_upload_failed': 'Photo upload failed: ',
      'status_sos_audio_failed': 'Audio attach failed: ',
      'status_sos_setup_refreshed': 'Chat setup refreshed. You can try sending now.',
      'error_chat_setup_failed': 'Chat setup failed. Please try again.',
      'error_sos_incomplete': 'SOS could not complete. Please try again.',
      'error_failed_load_chats': 'Failed to load chats',
      'dialog_sos_confirmation': 'SOS Triggered',
      'dialog_attachment_photo': 'Photo attached',
      'dialog_attachment_voice': 'Voice clip attached',
      'dialog_sent_attachment': 'Sent an attachment',
      'menu_disable_notifications': 'Disable notifications for this chat',
      'menu_enable_notifications': 'Enable notifications for this chat',
      'menu_delete_chat': 'Delete chat',
      'menu_mute': 'Mute',
      'menu_unmute': 'Unmute',
    },
    'kn': {
      'app_title': 'RescueLink',
      'emergency_prompt': 'In an Emergency?',
      'emergency_subtitle': 'Press the SOS button below to alert nearby responders',
      'become_responder': 'Become A Responder',
      'location_ready': 'Location: Ready',
      'location_not_ready': 'Location: Not Ready',
      'user_info': 'User Info',
      'total_responders': 'Total Responders',
      'nearby_5km': 'Nearby (5km)',
      'sign_in_title': 'RescueLink ಸೈನ್ ಇನ್',
      'sign_in': 'Sign In',
      'create_account': 'Create Account',
      'continue_guest': 'ಅತಿಥಿಯಾಗಿ ಮುಂದುವರಿಯಿರಿ',
      'language': 'ಭಾಷೆ',
      'button_cancel_sos': 'Cancel SOS',
      'button_view_map': 'View Map',
      'button_open_chat': 'Open Chat',
      'button_call_emergency': 'Call 112',
      'button_sign_out': 'Sign Out',
      'button_people_needing_help': 'People Needing Help',
      'button_voice_test': 'Voice Test',
      'button_flash_test': 'Flash Test',
      'button_responder_register': 'Register as Responder',
      'button_accept': 'Accept',
      'button_reject': 'Reject',
      'title_my_sos_chats': 'My SOS Chats',
      'title_responder_alerts': 'Responder Alerts',
      'title_map': 'Emergency Map',
      'title_profile': 'Profile',
      'title_settings': 'Settings',
      'title_accessibility': 'Accessibility Settings',
      'filter_active': 'Active',
      'filter_cancelled': 'Cancelled',
      'filter_all': 'All',
      'hint_search_case': 'Search by case ID or message',
      'hint_emergency_context': 'Describe emergency situation',
      'label_text_size': 'Text Size',
      'label_haptics': 'Haptics',
      'label_high_contrast': 'High Contrast Mode',
      'label_notifications': 'Notifications',
      'label_nearby_responders': 'Nearby Responders',
      'label_responder_online': 'Responder Online',
      'status_sos_received': '✓ SOS Received',
      'status_requesting_location': 'Requesting your location...',
      'status_no_location': 'Unable to determine location. Please try again.',
      'status_please_sign_in': 'Please sign in to view chats.',
      'status_chat_not_ready': 'Chat is not ready yet.',
      'status_not_signed_in': 'Not signed in',
      'status_location_ready': 'Location Ready',
      'status_location_not_ready': 'Location Not Ready',
      'status_sos_activated': 'SOS activated. Nearby responders have been notified.',
      'status_sos_photo_upload_failed': 'Photo upload failed: ',
      'status_sos_audio_failed': 'Audio attach failed: ',
      'status_sos_setup_refreshed': 'Chat setup refreshed. You can try sending now.',
      'error_chat_setup_failed': 'Chat setup failed. Please try again.',
      'error_sos_incomplete': 'SOS could not complete. Please try again.',
      'error_failed_load_chats': 'Failed to load chats',
      'dialog_sos_confirmation': 'SOS Triggered',
      'dialog_attachment_photo': 'Photo attached',
      'dialog_attachment_voice': 'Voice clip attached',
      'dialog_sent_attachment': 'Sent an attachment',
      'menu_disable_notifications': 'Disable notifications for this chat',
      'menu_enable_notifications': 'Enable notifications for this chat',
      'menu_delete_chat': 'Delete chat',
      'menu_mute': 'Mute',
      'menu_unmute': 'Unmute',
    },
    'bn': {
      'app_title': 'RescueLink',
      'emergency_prompt': 'In an Emergency?',
      'emergency_subtitle': 'Press the SOS button below to alert nearby responders',
      'become_responder': 'Become A Responder',
      'location_ready': 'Location: Ready',
      'location_not_ready': 'Location: Not Ready',
      'user_info': 'User Info',
      'total_responders': 'Total Responders',
      'nearby_5km': 'Nearby (5km)',
      'sign_in_title': 'RescueLink সাইন ইন',
      'sign_in': 'Sign In',
      'create_account': 'Create Account',
      'continue_guest': 'অতিথি হিসেবে চালিয়ে যান',
      'language': 'ভাষা',
      'button_cancel_sos': 'Cancel SOS',
      'button_view_map': 'View Map',
      'button_open_chat': 'Open Chat',
      'button_call_emergency': 'Call 112',
      'button_sign_out': 'Sign Out',
      'button_people_needing_help': 'People Needing Help',
      'button_voice_test': 'Voice Test',
      'button_flash_test': 'Flash Test',
      'button_responder_register': 'Register as Responder',
      'button_accept': 'Accept',
      'button_reject': 'Reject',
      'title_my_sos_chats': 'My SOS Chats',
      'title_responder_alerts': 'Responder Alerts',
      'title_map': 'Emergency Map',
      'title_profile': 'Profile',
      'title_settings': 'Settings',
      'title_accessibility': 'Accessibility Settings',
      'filter_active': 'Active',
      'filter_cancelled': 'Cancelled',
      'filter_all': 'All',
      'hint_search_case': 'Search by case ID or message',
      'hint_emergency_context': 'Describe emergency situation',
      'label_text_size': 'Text Size',
      'label_haptics': 'Haptics',
      'label_high_contrast': 'High Contrast Mode',
      'label_notifications': 'Notifications',
      'label_nearby_responders': 'Nearby Responders',
      'label_responder_online': 'Responder Online',
      'status_sos_received': '✓ SOS Received',
      'status_requesting_location': 'Requesting your location...',
      'status_no_location': 'Unable to determine location. Please try again.',
      'status_please_sign_in': 'Please sign in to view chats.',
      'status_chat_not_ready': 'Chat is not ready yet.',
      'status_not_signed_in': 'Not signed in',
      'status_location_ready': 'Location Ready',
      'status_location_not_ready': 'Location Not Ready',
      'status_sos_activated': 'SOS activated. Nearby responders have been notified.',
      'status_sos_photo_upload_failed': 'Photo upload failed: ',
      'status_sos_audio_failed': 'Audio attach failed: ',
      'status_sos_setup_refreshed': 'Chat setup refreshed. You can try sending now.',
      'error_chat_setup_failed': 'Chat setup failed. Please try again.',
      'error_sos_incomplete': 'SOS could not complete. Please try again.',
      'error_failed_load_chats': 'Failed to load chats',
      'dialog_sos_confirmation': 'SOS Triggered',
      'dialog_attachment_photo': 'Photo attached',
      'dialog_attachment_voice': 'Voice clip attached',
      'dialog_sent_attachment': 'Sent an attachment',
      'menu_disable_notifications': 'Disable notifications for this chat',
      'menu_enable_notifications': 'Enable notifications for this chat',
      'menu_delete_chat': 'Delete chat',
      'menu_mute': 'Mute',
      'menu_unmute': 'Unmute',
    },
    'mr': {
      'app_title': 'RescueLink',
      'emergency_prompt': 'In an Emergency?',
      'emergency_subtitle': 'Press the SOS button below to alert nearby responders',
      'become_responder': 'Become A Responder',
      'location_ready': 'Location: Ready',
      'location_not_ready': 'Location: Not Ready',
      'user_info': 'User Info',
      'total_responders': 'Total Responders',
      'nearby_5km': 'Nearby (5km)',
      'sign_in_title': 'RescueLink साइन इन',
      'sign_in': 'Sign In',
      'create_account': 'Create Account',
      'continue_guest': 'अतिथी म्हणून सुरू ठेवा',
      'language': 'भाषा',
      'button_cancel_sos': 'Cancel SOS',
      'button_view_map': 'View Map',
      'button_open_chat': 'Open Chat',
      'button_call_emergency': 'Call 112',
      'button_sign_out': 'Sign Out',
      'button_people_needing_help': 'People Needing Help',
      'button_voice_test': 'Voice Test',
      'button_flash_test': 'Flash Test',
      'button_responder_register': 'Register as Responder',
      'button_accept': 'Accept',
      'button_reject': 'Reject',
      'title_my_sos_chats': 'My SOS Chats',
      'title_responder_alerts': 'Responder Alerts',
      'title_map': 'Emergency Map',
      'title_profile': 'Profile',
      'title_settings': 'Settings',
      'title_accessibility': 'Accessibility Settings',
      'filter_active': 'Active',
      'filter_cancelled': 'Cancelled',
      'filter_all': 'All',
      'hint_search_case': 'Search by case ID or message',
      'hint_emergency_context': 'Describe emergency situation',
      'label_text_size': 'Text Size',
      'label_haptics': 'Haptics',
      'label_high_contrast': 'High Contrast Mode',
      'label_notifications': 'Notifications',
      'label_nearby_responders': 'Nearby Responders',
      'label_responder_online': 'Responder Online',
      'status_sos_received': '✓ SOS Received',
      'status_requesting_location': 'Requesting your location...',
      'status_no_location': 'Unable to determine location. Please try again.',
      'status_please_sign_in': 'Please sign in to view chats.',
      'status_chat_not_ready': 'Chat is not ready yet.',
      'status_not_signed_in': 'Not signed in',
      'status_location_ready': 'Location Ready',
      'status_location_not_ready': 'Location Not Ready',
      'status_sos_activated': 'SOS activated. Nearby responders have been notified.',
      'status_sos_photo_upload_failed': 'Photo upload failed: ',
      'status_sos_audio_failed': 'Audio attach failed: ',
      'status_sos_setup_refreshed': 'Chat setup refreshed. You can try sending now.',
      'error_chat_setup_failed': 'Chat setup failed. Please try again.',
      'error_sos_incomplete': 'SOS could not complete. Please try again.',
      'error_failed_load_chats': 'Failed to load chats',
      'dialog_sos_confirmation': 'SOS Triggered',
      'dialog_attachment_photo': 'Photo attached',
      'dialog_attachment_voice': 'Voice clip attached',
      'dialog_sent_attachment': 'Sent an attachment',
      'menu_disable_notifications': 'Disable notifications for this chat',
      'menu_enable_notifications': 'Enable notifications for this chat',
      'menu_delete_chat': 'Delete chat',
      'menu_mute': 'Mute',
      'menu_unmute': 'Unmute',
    },
    'gu': {
      'app_title': 'RescueLink',
      'emergency_prompt': 'In an Emergency?',
      'emergency_subtitle': 'Press the SOS button below to alert nearby responders',
      'become_responder': 'Become A Responder',
      'location_ready': 'Location: Ready',
      'location_not_ready': 'Location: Not Ready',
      'user_info': 'User Info',
      'total_responders': 'Total Responders',
      'nearby_5km': 'Nearby (5km)',
      'sign_in_title': 'RescueLink સાઇન ઇન',
      'sign_in': 'Sign In',
      'create_account': 'Create Account',
      'continue_guest': 'અતિથિ તરીકે ચાલુ રાખો',
      'language': 'ભાષા',
      'button_cancel_sos': 'Cancel SOS',
      'button_view_map': 'View Map',
      'button_open_chat': 'Open Chat',
      'button_call_emergency': 'Call 112',
      'button_sign_out': 'Sign Out',
      'button_people_needing_help': 'People Needing Help',
      'button_voice_test': 'Voice Test',
      'button_flash_test': 'Flash Test',
      'button_responder_register': 'Register as Responder',
      'button_accept': 'Accept',
      'button_reject': 'Reject',
      'title_my_sos_chats': 'My SOS Chats',
      'title_responder_alerts': 'Responder Alerts',
      'title_map': 'Emergency Map',
      'title_profile': 'Profile',
      'title_settings': 'Settings',
      'title_accessibility': 'Accessibility Settings',
      'filter_active': 'Active',
      'filter_cancelled': 'Cancelled',
      'filter_all': 'All',
      'hint_search_case': 'Search by case ID or message',
      'hint_emergency_context': 'Describe emergency situation',
      'label_text_size': 'Text Size',
      'label_haptics': 'Haptics',
      'label_high_contrast': 'High Contrast Mode',
      'label_notifications': 'Notifications',
      'label_nearby_responders': 'Nearby Responders',
      'label_responder_online': 'Responder Online',
      'status_sos_received': '✓ SOS Received',
      'status_requesting_location': 'Requesting your location...',
      'status_no_location': 'Unable to determine location. Please try again.',
      'status_please_sign_in': 'Please sign in to view chats.',
      'status_chat_not_ready': 'Chat is not ready yet.',
      'status_not_signed_in': 'Not signed in',
      'status_location_ready': 'Location Ready',
      'status_location_not_ready': 'Location Not Ready',
      'status_sos_activated': 'SOS activated. Nearby responders have been notified.',
      'status_sos_photo_upload_failed': 'Photo upload failed: ',
      'status_sos_audio_failed': 'Audio attach failed: ',
      'status_sos_setup_refreshed': 'Chat setup refreshed. You can try sending now.',
      'error_chat_setup_failed': 'Chat setup failed. Please try again.',
      'error_sos_incomplete': 'SOS could not complete. Please try again.',
      'error_failed_load_chats': 'Failed to load chats',
      'dialog_sos_confirmation': 'SOS Triggered',
      'dialog_attachment_photo': 'Photo attached',
      'dialog_attachment_voice': 'Voice clip attached',
      'dialog_sent_attachment': 'Sent an attachment',
      'menu_disable_notifications': 'Disable notifications for this chat',
      'menu_enable_notifications': 'Enable notifications for this chat',
      'menu_delete_chat': 'Delete chat',
      'menu_mute': 'Mute',
      'menu_unmute': 'Unmute',
    },
    'pa': {
      'app_title': 'RescueLink',
      'emergency_prompt': 'In an Emergency?',
      'emergency_subtitle': 'Press the SOS button below to alert nearby responders',
      'become_responder': 'Become A Responder',
      'location_ready': 'Location: Ready',
      'location_not_ready': 'Location: Not Ready',
      'user_info': 'User Info',
      'total_responders': 'Total Responders',
      'nearby_5km': 'Nearby (5km)',
      'sign_in_title': 'RescueLink ਸਾਇਨ ਇਨ',
      'sign_in': 'Sign In',
      'create_account': 'Create Account',
      'continue_guest': 'ਮਹਿਮਾਨ ਵਜੋਂ ਜਾਰੀ ਰੱਖੋ',
      'language': 'ਭਾਸ਼ਾ',
      'button_cancel_sos': 'Cancel SOS',
      'button_view_map': 'View Map',
      'button_open_chat': 'Open Chat',
      'button_call_emergency': 'Call 112',
      'button_sign_out': 'Sign Out',
      'button_people_needing_help': 'People Needing Help',
      'button_voice_test': 'Voice Test',
      'button_flash_test': 'Flash Test',
      'button_responder_register': 'Register as Responder',
      'button_accept': 'Accept',
      'button_reject': 'Reject',
      'title_my_sos_chats': 'My SOS Chats',
      'title_responder_alerts': 'Responder Alerts',
      'title_map': 'Emergency Map',
      'title_profile': 'Profile',
      'title_settings': 'Settings',
      'title_accessibility': 'Accessibility Settings',
      'filter_active': 'Active',
      'filter_cancelled': 'Cancelled',
      'filter_all': 'All',
      'hint_search_case': 'Search by case ID or message',
      'hint_emergency_context': 'Describe emergency situation',
      'label_text_size': 'Text Size',
      'label_haptics': 'Haptics',
      'label_high_contrast': 'High Contrast Mode',
      'label_notifications': 'Notifications',
      'label_nearby_responders': 'Nearby Responders',
      'label_responder_online': 'Responder Online',
      'status_sos_received': '✓ SOS Received',
      'status_requesting_location': 'Requesting your location...',
      'status_no_location': 'Unable to determine location. Please try again.',
      'status_please_sign_in': 'Please sign in to view chats.',
      'status_chat_not_ready': 'Chat is not ready yet.',
      'status_not_signed_in': 'Not signed in',
      'status_location_ready': 'Location Ready',
      'status_location_not_ready': 'Location Not Ready',
      'status_sos_activated': 'SOS activated. Nearby responders have been notified.',
      'status_sos_photo_upload_failed': 'Photo upload failed: ',
      'status_sos_audio_failed': 'Audio attach failed: ',
      'status_sos_setup_refreshed': 'Chat setup refreshed. You can try sending now.',
      'error_chat_setup_failed': 'Chat setup failed. Please try again.',
      'error_sos_incomplete': 'SOS could not complete. Please try again.',
      'error_failed_load_chats': 'Failed to load chats',
      'dialog_sos_confirmation': 'SOS Triggered',
      'dialog_attachment_photo': 'Photo attached',
      'dialog_attachment_voice': 'Voice clip attached',
      'dialog_sent_attachment': 'Sent an attachment',
      'menu_disable_notifications': 'Disable notifications for this chat',
      'menu_enable_notifications': 'Enable notifications for this chat',
      'menu_delete_chat': 'Delete chat',
      'menu_mute': 'Mute',
      'menu_unmute': 'Unmute',
    },
    'or': {
      'app_title': 'RescueLink',
      'emergency_prompt': 'In an Emergency?',
      'emergency_subtitle': 'Press the SOS button below to alert nearby responders',
      'become_responder': 'Become A Responder',
      'location_ready': 'Location: Ready',
      'location_not_ready': 'Location: Not Ready',
      'user_info': 'User Info',
      'total_responders': 'Total Responders',
      'nearby_5km': 'Nearby (5km)',
      'sign_in_title': 'RescueLink ସାଇନ ଇନ',
      'sign_in': 'Sign In',
      'create_account': 'Create Account',
      'continue_guest': 'ଅତିଥି ଭାବରେ ଜାରି ରଖନ୍ତୁ',
      'language': 'ଭାଷା',
      'button_cancel_sos': 'Cancel SOS',
      'button_view_map': 'View Map',
      'button_open_chat': 'Open Chat',
      'button_call_emergency': 'Call 112',
      'button_sign_out': 'Sign Out',
      'button_people_needing_help': 'People Needing Help',
      'button_voice_test': 'Voice Test',
      'button_flash_test': 'Flash Test',
      'button_responder_register': 'Register as Responder',
      'button_accept': 'Accept',
      'button_reject': 'Reject',
      'title_my_sos_chats': 'My SOS Chats',
      'title_responder_alerts': 'Responder Alerts',
      'title_map': 'Emergency Map',
      'title_profile': 'Profile',
      'title_settings': 'Settings',
      'title_accessibility': 'Accessibility Settings',
      'filter_active': 'Active',
      'filter_cancelled': 'Cancelled',
      'filter_all': 'All',
      'hint_search_case': 'Search by case ID or message',
      'hint_emergency_context': 'Describe emergency situation',
      'label_text_size': 'Text Size',
      'label_haptics': 'Haptics',
      'label_high_contrast': 'High Contrast Mode',
      'label_notifications': 'Notifications',
      'label_nearby_responders': 'Nearby Responders',
      'label_responder_online': 'Responder Online',
      'status_sos_received': '✓ SOS Received',
      'status_requesting_location': 'Requesting your location...',
      'status_no_location': 'Unable to determine location. Please try again.',
      'status_please_sign_in': 'Please sign in to view chats.',
      'status_chat_not_ready': 'Chat is not ready yet.',
      'status_not_signed_in': 'Not signed in',
      'status_location_ready': 'Location Ready',
      'status_location_not_ready': 'Location Not Ready',
      'status_sos_activated': 'SOS activated. Nearby responders have been notified.',
      'status_sos_photo_upload_failed': 'Photo upload failed: ',
      'status_sos_audio_failed': 'Audio attach failed: ',
      'status_sos_setup_refreshed': 'Chat setup refreshed. You can try sending now.',
      'error_chat_setup_failed': 'Chat setup failed. Please try again.',
      'error_sos_incomplete': 'SOS could not complete. Please try again.',
      'error_failed_load_chats': 'Failed to load chats',
      'dialog_sos_confirmation': 'SOS Triggered',
      'dialog_attachment_photo': 'Photo attached',
      'dialog_attachment_voice': 'Voice clip attached',
      'dialog_sent_attachment': 'Sent an attachment',
      'menu_disable_notifications': 'Disable notifications for this chat',
      'menu_enable_notifications': 'Enable notifications for this chat',
      'menu_delete_chat': 'Delete chat',
      'menu_mute': 'Mute',
      'menu_unmute': 'Unmute',
    },
    'ml': {
      'app_title': 'RescueLink',
      'emergency_prompt': 'In an Emergency?',
      'emergency_subtitle': 'Press the SOS button below to alert nearby responders',
      'become_responder': 'Become A Responder',
      'location_ready': 'Location: Ready',
      'location_not_ready': 'Location: Not Ready',
      'user_info': 'User Info',
      'total_responders': 'Total Responders',
      'nearby_5km': 'Nearby (5km)',
      'sign_in_title': 'RescueLink സൈൻ ഇൻ',
      'sign_in': 'Sign In',
      'create_account': 'Create Account',
      'continue_guest': 'അതിഥിയായി തുടരുക',
      'language': 'ഭാഷ',
      'button_cancel_sos': 'Cancel SOS',
      'button_view_map': 'View Map',
      'button_open_chat': 'Open Chat',
      'button_call_emergency': 'Call 112',
      'button_sign_out': 'Sign Out',
      'button_people_needing_help': 'People Needing Help',
      'button_voice_test': 'Voice Test',
      'button_flash_test': 'Flash Test',
      'button_responder_register': 'Register as Responder',
      'button_accept': 'Accept',
      'button_reject': 'Reject',
      'title_my_sos_chats': 'My SOS Chats',
      'title_responder_alerts': 'Responder Alerts',
      'title_map': 'Emergency Map',
      'title_profile': 'Profile',
      'title_settings': 'Settings',
      'title_accessibility': 'Accessibility Settings',
      'filter_active': 'Active',
      'filter_cancelled': 'Cancelled',
      'filter_all': 'All',
      'hint_search_case': 'Search by case ID or message',
      'hint_emergency_context': 'Describe emergency situation',
      'label_text_size': 'Text Size',
      'label_haptics': 'Haptics',
      'label_high_contrast': 'High Contrast Mode',
      'label_notifications': 'Notifications',
      'label_nearby_responders': 'Nearby Responders',
      'label_responder_online': 'Responder Online',
      'status_sos_received': '✓ SOS Received',
      'status_requesting_location': 'Requesting your location...',
      'status_no_location': 'Unable to determine location. Please try again.',
      'status_please_sign_in': 'Please sign in to view chats.',
      'status_chat_not_ready': 'Chat is not ready yet.',
      'status_not_signed_in': 'Not signed in',
      'status_location_ready': 'Location Ready',
      'status_location_not_ready': 'Location Not Ready',
      'status_sos_activated': 'SOS activated. Nearby responders have been notified.',
      'status_sos_photo_upload_failed': 'Photo upload failed: ',
      'status_sos_audio_failed': 'Audio attach failed: ',
      'status_sos_setup_refreshed': 'Chat setup refreshed. You can try sending now.',
      'error_chat_setup_failed': 'Chat setup failed. Please try again.',
      'error_sos_incomplete': 'SOS could not complete. Please try again.',
      'error_failed_load_chats': 'Failed to load chats',
      'dialog_sos_confirmation': 'SOS Triggered',
      'dialog_attachment_photo': 'Photo attached',
      'dialog_attachment_voice': 'Voice clip attached',
      'dialog_sent_attachment': 'Sent an attachment',
      'menu_disable_notifications': 'Disable notifications for this chat',
      'menu_enable_notifications': 'Enable notifications for this chat',
      'menu_delete_chat': 'Delete chat',
      'menu_mute': 'Mute',
      'menu_unmute': 'Unmute',
    },
    'zh': {
      'app_title': 'RescueLink',
      'emergency_prompt': 'In an Emergency?',
      'emergency_subtitle': 'Press the SOS button below to alert nearby responders',
      'become_responder': 'Become A Responder',
      'location_ready': 'Location: Ready',
      'location_not_ready': 'Location: Not Ready',
      'user_info': 'User Info',
      'total_responders': 'Total Responders',
      'nearby_5km': 'Nearby (5km)',
      'sign_in_title': 'RescueLink 登录',
      'sign_in': 'Sign In',
      'create_account': 'Create Account',
      'continue_guest': '以访客身份继续',
      'language': '语言',
      'button_cancel_sos': 'Cancel SOS',
      'button_view_map': 'View Map',
      'button_open_chat': 'Open Chat',
      'button_call_emergency': 'Call 112',
      'button_sign_out': 'Sign Out',
      'button_people_needing_help': 'People Needing Help',
      'button_voice_test': 'Voice Test',
      'button_flash_test': 'Flash Test',
      'button_responder_register': 'Register as Responder',
      'button_accept': 'Accept',
      'button_reject': 'Reject',
      'title_my_sos_chats': 'My SOS Chats',
      'title_responder_alerts': 'Responder Alerts',
      'title_map': 'Emergency Map',
      'title_profile': 'Profile',
      'title_settings': 'Settings',
      'title_accessibility': 'Accessibility Settings',
      'filter_active': 'Active',
      'filter_cancelled': 'Cancelled',
      'filter_all': 'All',
      'hint_search_case': 'Search by case ID or message',
      'hint_emergency_context': 'Describe emergency situation',
      'label_text_size': 'Text Size',
      'label_haptics': 'Haptics',
      'label_high_contrast': 'High Contrast Mode',
      'label_notifications': 'Notifications',
      'label_nearby_responders': 'Nearby Responders',
      'label_responder_online': 'Responder Online',
      'status_sos_received': '✓ SOS Received',
      'status_requesting_location': 'Requesting your location...',
      'status_no_location': 'Unable to determine location. Please try again.',
      'status_please_sign_in': 'Please sign in to view chats.',
      'status_chat_not_ready': 'Chat is not ready yet.',
      'status_not_signed_in': 'Not signed in',
      'status_location_ready': 'Location Ready',
      'status_location_not_ready': 'Location Not Ready',
      'status_sos_activated': 'SOS activated. Nearby responders have been notified.',
      'status_sos_photo_upload_failed': 'Photo upload failed: ',
      'status_sos_audio_failed': 'Audio attach failed: ',
      'status_sos_setup_refreshed': 'Chat setup refreshed. You can try sending now.',
      'error_chat_setup_failed': 'Chat setup failed. Please try again.',
      'error_sos_incomplete': 'SOS could not complete. Please try again.',
      'error_failed_load_chats': 'Failed to load chats',
      'dialog_sos_confirmation': 'SOS Triggered',
      'dialog_attachment_photo': 'Photo attached',
      'dialog_attachment_voice': 'Voice clip attached',
      'dialog_sent_attachment': 'Sent an attachment',
      'menu_disable_notifications': 'Disable notifications for this chat',
      'menu_enable_notifications': 'Enable notifications for this chat',
      'menu_delete_chat': 'Delete chat',
      'menu_mute': 'Mute',
      'menu_unmute': 'Unmute',
    },
    'ja': {
      'app_title': 'RescueLink',
      'emergency_prompt': 'In an Emergency?',
      'emergency_subtitle': 'Press the SOS button below to alert nearby responders',
      'become_responder': 'Become A Responder',
      'location_ready': 'Location: Ready',
      'location_not_ready': 'Location: Not Ready',
      'user_info': 'User Info',
      'total_responders': 'Total Responders',
      'nearby_5km': 'Nearby (5km)',
      'sign_in_title': 'RescueLink サインイン',
      'sign_in': 'Sign In',
      'create_account': 'Create Account',
      'continue_guest': 'ゲストとして続行',
      'language': '言語',
      'button_cancel_sos': 'Cancel SOS',
      'button_view_map': 'View Map',
      'button_open_chat': 'Open Chat',
      'button_call_emergency': 'Call 112',
      'button_sign_out': 'Sign Out',
      'button_people_needing_help': 'People Needing Help',
      'button_voice_test': 'Voice Test',
      'button_flash_test': 'Flash Test',
      'button_responder_register': 'Register as Responder',
      'button_accept': 'Accept',
      'button_reject': 'Reject',
      'title_my_sos_chats': 'My SOS Chats',
      'title_responder_alerts': 'Responder Alerts',
      'title_map': 'Emergency Map',
      'title_profile': 'Profile',
      'title_settings': 'Settings',
      'title_accessibility': 'Accessibility Settings',
      'filter_active': 'Active',
      'filter_cancelled': 'Cancelled',
      'filter_all': 'All',
      'hint_search_case': 'Search by case ID or message',
      'hint_emergency_context': 'Describe emergency situation',
      'label_text_size': 'Text Size',
      'label_haptics': 'Haptics',
      'label_high_contrast': 'High Contrast Mode',
      'label_notifications': 'Notifications',
      'label_nearby_responders': 'Nearby Responders',
      'label_responder_online': 'Responder Online',
      'status_sos_received': '✓ SOS Received',
      'status_requesting_location': 'Requesting your location...',
      'status_no_location': 'Unable to determine location. Please try again.',
      'status_please_sign_in': 'Please sign in to view chats.',
      'status_chat_not_ready': 'Chat is not ready yet.',
      'status_not_signed_in': 'Not signed in',
      'status_location_ready': 'Location Ready',
      'status_location_not_ready': 'Location Not Ready',
      'status_sos_activated': 'SOS activated. Nearby responders have been notified.',
      'status_sos_photo_upload_failed': 'Photo upload failed: ',
      'status_sos_audio_failed': 'Audio attach failed: ',
      'status_sos_setup_refreshed': 'Chat setup refreshed. You can try sending now.',
      'error_chat_setup_failed': 'Chat setup failed. Please try again.',
      'error_sos_incomplete': 'SOS could not complete. Please try again.',
      'error_failed_load_chats': 'Failed to load chats',
      'dialog_sos_confirmation': 'SOS Triggered',
      'dialog_attachment_photo': 'Photo attached',
      'dialog_attachment_voice': 'Voice clip attached',
      'dialog_sent_attachment': 'Sent an attachment',
      'menu_disable_notifications': 'Disable notifications for this chat',
      'menu_enable_notifications': 'Enable notifications for this chat',
      'menu_delete_chat': 'Delete chat',
      'menu_mute': 'Mute',
      'menu_unmute': 'Unmute',
    },
    'ko': {
      'app_title': 'RescueLink',
      'emergency_prompt': 'In an Emergency?',
      'emergency_subtitle': 'Press the SOS button below to alert nearby responders',
      'become_responder': 'Become A Responder',
      'location_ready': 'Location: Ready',
      'location_not_ready': 'Location: Not Ready',
      'user_info': 'User Info',
      'total_responders': 'Total Responders',
      'nearby_5km': 'Nearby (5km)',
      'sign_in_title': 'RescueLink 로그인',
      'sign_in': 'Sign In',
      'create_account': 'Create Account',
      'continue_guest': '게스트로 계속',
      'language': '언어',
      'button_cancel_sos': 'Cancel SOS',
      'button_view_map': 'View Map',
      'button_open_chat': 'Open Chat',
      'button_call_emergency': 'Call 112',
      'button_sign_out': 'Sign Out',
      'button_people_needing_help': 'People Needing Help',
      'button_voice_test': 'Voice Test',
      'button_flash_test': 'Flash Test',
      'button_responder_register': 'Register as Responder',
      'button_accept': 'Accept',
      'button_reject': 'Reject',
      'title_my_sos_chats': 'My SOS Chats',
      'title_responder_alerts': 'Responder Alerts',
      'title_map': 'Emergency Map',
      'title_profile': 'Profile',
      'title_settings': 'Settings',
      'title_accessibility': 'Accessibility Settings',
      'filter_active': 'Active',
      'filter_cancelled': 'Cancelled',
      'filter_all': 'All',
      'hint_search_case': 'Search by case ID or message',
      'hint_emergency_context': 'Describe emergency situation',
      'label_text_size': 'Text Size',
      'label_haptics': 'Haptics',
      'label_high_contrast': 'High Contrast Mode',
      'label_notifications': 'Notifications',
      'label_nearby_responders': 'Nearby Responders',
      'label_responder_online': 'Responder Online',
      'status_sos_received': '✓ SOS Received',
      'status_requesting_location': 'Requesting your location...',
      'status_no_location': 'Unable to determine location. Please try again.',
      'status_please_sign_in': 'Please sign in to view chats.',
      'status_chat_not_ready': 'Chat is not ready yet.',
      'status_not_signed_in': 'Not signed in',
      'status_location_ready': 'Location Ready',
      'status_location_not_ready': 'Location Not Ready',
      'status_sos_activated': 'SOS activated. Nearby responders have been notified.',
      'status_sos_photo_upload_failed': 'Photo upload failed: ',
      'status_sos_audio_failed': 'Audio attach failed: ',
      'status_sos_setup_refreshed': 'Chat setup refreshed. You can try sending now.',
      'error_chat_setup_failed': 'Chat setup failed. Please try again.',
      'error_sos_incomplete': 'SOS could not complete. Please try again.',
      'error_failed_load_chats': 'Failed to load chats',
      'dialog_sos_confirmation': 'SOS Triggered',
      'dialog_attachment_photo': 'Photo attached',
      'dialog_attachment_voice': 'Voice clip attached',
      'dialog_sent_attachment': 'Sent an attachment',
      'menu_disable_notifications': 'Disable notifications for this chat',
      'menu_enable_notifications': 'Enable notifications for this chat',
      'menu_delete_chat': 'Delete chat',
      'menu_mute': 'Mute',
      'menu_unmute': 'Unmute',
    },
  };

  String t(String key) {
    return _strings[_languageCode]?[key] ?? _strings['en']?[key] ?? key;
  }

  void configureForLocale(Locale locale) {
    final country = (locale.countryCode ?? '').toUpperCase();
    final language = locale.languageCode.toLowerCase();

    final preset = _regionLanguagePresets['$country:$language'] ??
        _regionLanguagePresets['$country:en'] ??
        <String>[language, 'en'];

    final options = <String>{...preset, language, 'en'};
    if (options.length == 1 && options.contains('en')) {
      options.addAll(<String>['hi', 'ta']);
    }
    _availableLanguageCodes = options.toList();

    if (_availableLanguageCodes.contains(language)) {
      _languageCode = language;
    } else if (!_availableLanguageCodes.contains(_languageCode)) {
      _languageCode = _availableLanguageCodes.first;
    }

    notifyListeners();
  }

  void setLanguage(String languageCode) {
    if (!_availableLanguageCodes.contains(languageCode)) {
      return;
    }
    if (_languageCode == languageCode) {
      return;
    }
    _languageCode = languageCode;
    notifyListeners();
  }

  void setTextScaleFactor(double value) {
    final next = value.clamp(0.85, 1.6);
    if (_textScaleFactor == next) {
      return;
    }
    _textScaleFactor = next;
    notifyListeners();
  }

  void setHapticsEnabled(bool enabled) {
    if (_hapticsEnabled == enabled) {
      return;
    }
    _hapticsEnabled = enabled;
    notifyListeners();
  }

  void setSosFlashEnabled(bool enabled) {
    if (_sosFlashEnabled == enabled) {
      return;
    }
    _sosFlashEnabled = enabled;
    notifyListeners();
  }

  void setHighContrastEnabled(bool enabled) {
    if (_highContrastEnabled == enabled) {
      return;
    }
    _highContrastEnabled = enabled;
    notifyListeners();
  }

  void setNotificationsEnabled(bool enabled) {
    if (_notificationsEnabled == enabled) {
      return;
    }
    _notificationsEnabled = enabled;
    notifyListeners();
  }

  String localizedCrisisCategory(String category) {
    switch (category.trim().toLowerCase()) {
      case 'fire emergency':
        return t('category_fire_emergency');
      case 'medical emergency':
        return t('category_medical_emergency');
      case 'disaster evacuation':
        return t('category_disaster_evacuation');
      case 'essential supply need':
        return t('category_essential_supply_need');
      case 'elderly assistance':
        return t('category_elderly_assistance');
      case 'women safety':
        return t('category_women_safety');
      case 'child safety':
        return t('category_child_safety');
      case 'search & rescue':
        return t('category_search_and_rescue');
      case 'water rescue emergency':
        return t('category_water_rescue_emergency');
      case 'railway hazard emergency':
        return t('category_railway_hazard_emergency');
      case 'entrapment rescue':
        return t('category_entrapment_rescue');
      case 'animal/insect attack':
        return t('category_animal_insect_attack');
      case 'general emergency':
        return t('category_general_emergency');
      case 'medical safety emergency':
        return t('category_medical_safety_emergency');
      case 'rescue emergency':
        return t('category_rescue_emergency');
      default:
        return category;
    }
  }

  String localizedSkill(String skill) {
    final normalized = skill.trim().toLowerCase();
    switch (normalized) {
      case 'fire & rescue':
      case 'responder_skill_fire_and_rescue':
        return t('skill_fire_rescue');
      case 'medical emergency':
      case 'responder_skill_medical_emergency':
        return t('skill_medical_emergency');
      case 'search & rescue':
      case 'responder_skill_search_and_rescue':
        return t('skill_search_rescue');
      case 'shelter & evacuation':
      case 'responder_skill_shelter_and_evacuation':
        return t('skill_shelter_evacuation');
      case 'food & water supply':
      case 'responder_skill_food_and_water_supply':
        return t('skill_food_water_supply');
      case 'elderly assist':
      case 'responder_skill_elderly_assist':
        return t('skill_elderly_assist');
      case 'women safety':
      case 'responder_skill_women_safety':
        return t('skill_women_safety');
      case 'child safety':
      case 'responder_skill_child_safety':
        return t('skill_child_safety');
      case 'general support':
      case 'responder_skill_general_support':
        return t('skill_general_support');
      default:
        return skill;
    }
  }

  String localizedResponderType(String responderType) {
    final normalized = responderType.trim().toLowerCase();
    switch (normalized) {
      case 'community volunteer':
      case 'responder_type_community_volunteer':
        return t('responder_type_community_volunteer');
      case 'medical professional':
      case 'responder_type_medical_professional':
        return t('responder_type_medical_professional');
      case 'firefighter':
      case 'responder_type_firefighter':
        return t('responder_type_firefighter');
      case 'police':
      case 'responder_type_police':
        return t('responder_type_police');
      case 'off-duty authority':
      case 'responder_type_off_duty_authority':
        return t('responder_type_off_duty_authority');
      case 'civil defense':
      case 'responder_type_civil_defense':
        return t('responder_type_civil_defense');
      case 'ngo worker':
      case 'responder_type_ngo_worker':
        return t('responder_type_ngo_worker');
      case 'logistics provider':
      case 'responder_type_logistics_provider':
        return t('responder_type_logistics_provider');
      case 'shelter host':
      case 'responder_type_shelter_host':
        return t('responder_type_shelter_host');
      default:
        return responderType;
    }
  }
}
