// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZxkGqoVI-UrDtHJ-Bvk4leUnkhzuIBRs',
    appId: '1:858135673489:web:a8503ffdf23c690fff1d30',
    messagingSenderId: '858135673489',
    projectId: 'instascrappy-8b1d8',
    authDomain: 'instascrappy-8b1d8.firebaseapp.com',
    storageBucket: 'instascrappy-8b1d8.firebasestorage.app',
    measurementId: 'G-265WXS8K0W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn7mZX8kaRsxeLggtGe9KxvTN-cfCd7ko',
    appId: '1:859507123714:android:1a09cca6e81d56908de91b',
    messagingSenderId: '859507123714',
    projectId: 'rescue-link-2026',
    storageBucket: 'rescue-link-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmvMQVViBRf1HLRuuv_VEWcNNekhh7Np4',
    appId: '1:859507123714:ios:ce47445402e137198de91b',
    messagingSenderId: '859507123714',
    projectId: 'rescue-link-2026',
    storageBucket: 'rescue-link-2026.firebasestorage.app',
    iosBundleId: 'com.gdg.rescueLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAC1dy5d9qUsFIAGdVI7q38xSag8o78568',
    appId: '1:858135673489:ios:1ad8fde3097fe182ff1d30',
    messagingSenderId: '858135673489',
    projectId: 'instascrappy-8b1d8',
    storageBucket: 'instascrappy-8b1d8.firebasestorage.app',
    iosBundleId: 'com.gdg.rescueLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZxkGqoVI-UrDtHJ-Bvk4leUnkhzuIBRs',
    appId: '1:858135673489:web:5273081f4475c556ff1d30',
    messagingSenderId: '858135673489',
    projectId: 'instascrappy-8b1d8',
    authDomain: 'instascrappy-8b1d8.firebaseapp.com',
    storageBucket: 'instascrappy-8b1d8.firebasestorage.app',
    measurementId: 'G-48EJPR59ET',
  );

}